// GENERATED by `pnpm gen:liability` from docs/engine-errata.md. Do not edit:
// change the errata table, then regenerate (errata.test.ts checks it).
import type { Erratum } from './errata';

export const ENGINE_ERRATA: readonly Erratum[] = [
	{
		"id": "ER-1",
		"keyedOn": "run",
		"firstAffected": "0.0.0",
		"fixedIn": "0.7.0",
		"severity": "High",
		"appliesWhen": "Catchment rain has blank days that CHIRPS filled",
		"summary": "CHIRPS filled the gaps without bias correction, so a filled year could run far too dry or wet",
		"source": "engine-audit.md B1; model.md §2.4b"
	},
	{
		"id": "ER-2",
		"keyedOn": "run",
		"firstAffected": "0.0.0",
		"fixedIn": "0.15.0",
		"severity": "High",
		"appliesWhen": "Missing catchment rain was recorded as zeros",
		"summary": "A run of zeros counted as dry days and blocked the CHIRPS fill, running the catchment dry over those days",
		"source": "engine-audit.md B2; model.md §2.4c"
	},
	{
		"id": "ER-3",
		"keyedOn": "run",
		"firstAffected": "0.15.0",
		"fixedIn": "0.20.0",
		"severity": "Medium",
		"appliesWhen": "A run ends in a zero-rain run set aside as missing whose reading day holds a multi-day accumulation",
		"summary": "The run was filled from CHIRPS and the accumulated reading was also kept, so that rain was counted twice",
		"source": "engine-audit.md B4; model.md §2.4d"
	},
	{
		"id": "ER-4",
		"keyedOn": "run",
		"firstAffected": "0.0.0",
		"fixedIn": "0.27.1",
		"severity": "High",
		"appliesWhen": "Flow shares (manual, or a high/low split) add up to more than the catchment",
		"summary": "The run went ahead and the farms made more runoff than the catchment's natural flow, lifting the outflow and hiding EWR failures",
		"source": "model.md §2.5 (overAllocationError)"
	},
	{
		"id": "ER-5",
		"keyedOn": "run",
		"firstAffected": "0.0.0",
		"fixedIn": "0.45.0",
		"severity": "High",
		"appliesWhen": "Simulation start or end unset, and the rain series padded with blanks beyond its readings",
		"summary": "The default run window covered the blanks, which ran as 0 mm and distorted every whole-run figure",
		"source": "engine-audit.md D1; model.md §2.1"
	},
	{
		"id": "ER-6",
		"keyedOn": "fit",
		"firstAffected": "0.5.0",
		"fixedIn": "1.22.0",
		"severity": "Medium",
		"appliesWhen": "The run's parameters come from an automatic fit on a record with suspect days or flood days beyond the gauged range",
		"summary": "Those days weighed in the fit's objective like any other, so the fit could chase a stuck logger or a rating-curve extrapolation",
		"source": "engine-audit.md C2; model.md §2.10h"
	},
	{
		"id": "ER-7",
		"keyedOn": "run",
		"firstAffected": "0.16.0",
		"fixedIn": "0.19.0",
		"severity": "Medium",
		"appliesWhen": "A transfer into a dam that loses water to evaporation or seepage",
		"summary": "The destination dam was topped up short by that day's losses, so it could sit under its dead storage and supply nothing while the source had water to send",
		"source": "engine-audit.md N4; model.md §2.6"
	},
	{
		"id": "ER-8",
		"keyedOn": "run",
		"firstAffected": "0.16.0",
		"fixedIn": "0.21.1",
		"severity": "Low",
		"appliesWhen": "A very shallow dam with an area exponent above 1",
		"summary": "A day's evaporation could exceed 1/b of the dam, so a fuller dam ended the day with less water than a lower one and more demand could raise a farm's supply fraction",
		"source": "engine-audit.md N2; model.md §2.7a"
	},
	{
		"id": "ER-9",
		"keyedOn": "run",
		"firstAffected": "0.35.0",
		"fixedIn": "1.29.0",
		"severity": "Low",
		"appliesWhen": "A transfer into a full dam that has a fixed release",
		"summary": "The dam's room ignored the release, so it sat one release below full instead of taking back what it released",
		"source": "engine-audit.md N4; model.md §2.6"
	},
	{
		"id": "ER-10",
		"keyedOn": "run",
		"firstAffected": "0.32.0",
		"fixedIn": "1.34.0",
		"severity": "High",
		"appliesWhen": "Rarely (the rarity is here, not in the severity: when it hits, the figures are another farm's), when the JavaScript engine's optimising compiler timed a run a certain way (seen once, on a busy test machine), on a run with two or more farms or water users",
		"summary": "A V8 miscompile could give a farm or water user another one's assurance of supply (reliability, annual reliability, failure runs) under its own name; its daily series and every other summary were right, and the run's self-checks didn't look at it",
		"source": "engine-audit.md V1; model.md §2.11a"
	},
	{
		"id": "ER-11",
		"keyedOn": "run",
		"firstAffected": "0.16.0",
		"fixedIn": "1.36.0",
		"severity": "Medium",
		"appliesWhen": "Two or more transfer rules of one priority from one dam at different reserves (counting a rule active that month at rate 0)",
		"summary": "The rules shared the free water above the lowest reserve among them, so the higher-reserve rules together could take the dam below their own reserves (a rule moving nothing lowered the floor for the rest)",
		"source": "engine-audit.md N6; model.md §2.6"
	},
	{
		"id": "ER-12",
		"keyedOn": "run",
		"firstAffected": "1.8.0",
		"fixedIn": "1.57.0",
		"severity": "Low",
		"appliesWhen": "A primary or emergency borehole pumping into a farm's dam, on a day its crop requirement came out as float noise (the soil-water store's rain an ulp short of the need) or off-take water arrived an ulp short of the demand",
		"summary": "A demand of 10⁻¹² m³ or less counted as the dam being drawn for demand, so the borehole topped the dam up by up to a day's capacity (495 and 1 590 m³ in the cases found), using its annual cap and depleting the river",
		"source": "model.md §2.3, §2.7d; found by verify/ phase 2a"
	}
];
