// GENERATED by `pnpm gen:liability` from docs/engine-errata.md. Do not edit:
// change the errata table, then regenerate (errata.test.ts checks it).
import type { Erratum } from './errata';

export const ENGINE_ERRATA: readonly Erratum[] = [
	{
		"id": "ER-1",
		"firstAffected": "0.0.0",
		"fixedIn": "0.7.0",
		"severity": "High",
		"appliesWhen": "Catchment rain has blank days that CHIRPS filled",
		"summary": "CHIRPS filled the gaps without bias correction, so a filled year could run far too dry or wet",
		"source": "engine-audit.md B1; model.md §2.4b"
	},
	{
		"id": "ER-2",
		"firstAffected": "0.0.0",
		"fixedIn": "0.15.0",
		"severity": "High",
		"appliesWhen": "Missing catchment rain was recorded as zeros",
		"summary": "A run of zeros counted as dry days and blocked the CHIRPS fill, running the catchment dry over those days",
		"source": "engine-audit.md B2; model.md §2.4c"
	},
	{
		"id": "ER-3",
		"firstAffected": "0.15.0",
		"fixedIn": "0.20.0",
		"severity": "Medium",
		"appliesWhen": "A run ends in a zero-rain run set aside as missing whose reading day holds a multi-day accumulation",
		"summary": "The run was filled from CHIRPS and the accumulated reading was also kept, so that rain was counted twice",
		"source": "engine-audit.md B4; model.md §2.4d"
	},
	{
		"id": "ER-4",
		"firstAffected": "0.0.0",
		"fixedIn": "0.27.1",
		"severity": "High",
		"appliesWhen": "Flow shares (manual, or a high/low split) add up to more than the catchment",
		"summary": "The run went ahead and the farms made more runoff than the catchment's natural flow, lifting the outflow and hiding EWR failures",
		"source": "model.md §2.5 (overAllocationError)"
	},
	{
		"id": "ER-5",
		"firstAffected": "0.0.0",
		"fixedIn": "0.45.0",
		"severity": "High",
		"appliesWhen": "Simulation start or end unset, and the rain series padded with blanks beyond its readings",
		"summary": "The default run window covered the blanks, which ran as 0 mm and distorted every whole-run figure",
		"source": "engine-audit.md D1; model.md §2.1"
	},
	{
		"id": "ER-6",
		"firstAffected": "0.5.0",
		"fixedIn": "1.22.0",
		"severity": "Medium",
		"appliesWhen": "An automatic calibration on a record with suspect days or flood days beyond the gauged range",
		"summary": "Those days weighed in the fit's objective like any other, so a fit could chase a stuck logger or a rating-curve extrapolation",
		"source": "engine-audit.md C2; model.md §2.10h"
	}
];
