// The source text of the generated liability modules, shared by the
// generator (scripts/gen-liability.ts) and the tests that check each is
// current.
import type { Erratum } from './errata';
import type { Limitation } from './limitations';
import type { MethodologyVersion } from './methodology';

export function renderLimitationsModule(list: readonly Limitation[]): string {
	return [
		'// GENERATED by `pnpm gen:liability` from docs/engine-audit.md. Do not edit:',
		'// change the audit item, then regenerate (limitations.test.ts checks it).',
		"import type { Limitation } from './limitations';",
		'',
		`export const KNOWN_LIMITATIONS: readonly Limitation[] = ${JSON.stringify(list, null, '\t')};`,
		''
	].join('\n');
}

export function renderErrataModule(list: readonly Erratum[]): string {
	return [
		'// GENERATED by `pnpm gen:liability` from docs/engine-errata.md. Do not edit:',
		'// change the errata table, then regenerate (errata.test.ts checks it).',
		"import type { Erratum } from './errata';",
		'',
		`export const ENGINE_ERRATA: readonly Erratum[] = ${JSON.stringify(list, null, '\t')};`,
		''
	].join('\n');
}

export function renderMethodologyModule(versions: readonly MethodologyVersion[]): string {
	const current = versions[versions.length - 1];
	if (!current) throw new Error('docs/methodology has no v<N>.md');
	return [
		'// GENERATED by `pnpm gen:liability` from docs/methodology/v<N>.md. Do not edit:',
		'// add a new version, then regenerate (methodology.test.ts checks it).',
		"import type { MethodologyVersion } from './methodology';",
		'',
		'/** Every published version, oldest first. */',
		`export const METHODOLOGY_VERSIONS: readonly MethodologyVersion[] = ${JSON.stringify(versions, null, '\t')};`,
		'',
		'/** The current version: new sign-offs and evidence packs cite it. */',
		`export const METHODOLOGY: MethodologyVersion = METHODOLOGY_VERSIONS[${versions.length - 1}]!;`,
		''
	].join('\n');
}

export function renderMethodologyTextModule(current: MethodologyVersion, text: string): string {
	return [
		'// GENERATED by `pnpm gen:liability` from docs/methodology. Do not edit.',
		'// The current methodology statement\'s text, in a module of its own so only',
		'// the pages that print it load it (the package export "./methodology").',
		'',
		`export const METHODOLOGY_VERSION = ${JSON.stringify(current.version)};`,
		`export const METHODOLOGY_TEXT = ${JSON.stringify(text)};`,
		''
	].join('\n');
}
