// The source text of limitations.generated.ts, shared by the generator
// (scripts/gen-limitations.ts) and the test that checks it is current.
import type { Limitation } from './limitations';

export function renderLimitationsModule(list: readonly Limitation[]): string {
	return [
		'// GENERATED by `pnpm gen:limitations` from docs/engine-audit.md. Do not edit:',
		'// change the audit item, then regenerate (limitations.test.ts checks it).',
		"import type { Limitation } from './limitations';",
		'',
		`export const KNOWN_LIMITATIONS: readonly Limitation[] = ${JSON.stringify(list, null, '\t')};`,
		''
	].join('\n');
}
