// GENERATED by `pnpm gen:limitations` from docs/engine-audit.md. Do not edit:
// change the audit item, then regenerate (limitations.test.ts checks it).
import type { Limitation } from './limitations';

export const KNOWN_LIMITATIONS: readonly Limitation[] = [
	{
		"id": "N1",
		"source": "finding",
		"severity": "Medium",
		"title": "Irrigation efficiency and return flow don't add up",
		"status": "Decided (persona recommendation, 2026-09-24; pending the hydrologist) — engine 0.16.0"
	},
	{
		"id": "N2",
		"source": "finding",
		"severity": "High (dam-dominated farms)",
		"title": "Dam evaporation and seepage are ignored",
		"status": "Decided (persona recommendation, 2026-09-24; pending the hydrologist) — engine 0.16.0"
	},
	{
		"id": "N3",
		"source": "finding",
		"severity": "Medium",
		"title": "Effective rain is applied day by day with no carry-over",
		"status": "Decided (persona recommendation, 2026-09-24; pending the hydrologist), engine 0.14.0"
	},
	{
		"id": "N5",
		"source": "finding",
		"severity": "Medium (where boreholes pump near the river)",
		"title": "Groundwater was not modelled",
		"status": "Built (engine 0.23.0, roadmap WP-1.34, migration 012), off by default; pending the hydrologist"
	},
	{
		"id": "N4",
		"source": "finding",
		"severity": "Low",
		"title": "Transfers ignore the receiving dam's free space, and the source's irrigation comes second",
		"status": "Decided (persona recommendation, 2026-09-24; pending the hydrologist) — engine 0.16.0"
	},
	{
		"id": "B2",
		"source": "finding",
		"severity": "High (catchments whose rain record has gaps exported as zeros)",
		"title": "Missing catchment rain recorded as 0 runs the catchment dry",
		"status": "Fixed, engine 0.15.0 (CR-20, issue #2; operator decision 2026-09-24, pending the hydrologist's confirmation of the flagged runs)"
	},
	{
		"id": "B3",
		"source": "finding",
		"severity": "Medium (catchments whose rain network changed over the record)",
		"title": "The CHIRPS factors blend eras that disagree",
		"status": "Warned, engine 0.18.0 (CR-20)"
	},
	{
		"id": "Q3",
		"source": "quirk",
		"severity": null,
		"title": "Transfer order / spill at the receiver",
		"status": "Decided (persona recommendation, 2026-09-24; pending the hydrologist) — engine 0.16.0"
	},
	{
		"id": "Q5",
		"source": "quirk",
		"severity": null,
		"title": "Irrigation may empty the dam",
		"status": "Decided (persona recommendation, 2026-09-24; pending the hydrologist) — engine 0.16.0"
	},
	{
		"id": "Q6",
		"source": "quirk",
		"severity": null,
		"title": "Threshold on the demand offset",
		"status": "The larger issue, no carry-over, is N3: decided on a persona recommendation (engine 0.14.0, soil-water store), pending the hydrologist"
	},
	{
		"id": "Q11",
		"source": "quirk",
		"severity": null,
		"title": "Equitable target ignores the network",
		"status": "Decided (simulated CMA-assessor recommendation, 2026-09-24; pending the real assessor and hydrologist) — engine 0.17.0, labels only"
	},
	{
		"id": "Q13",
		"source": "quirk",
		"severity": null,
		"title": "EWR cut on a farm with no demand",
		"status": "Decided (simulated CMA-assessor recommendation, 2026-09-24; pending the real assessor and hydrologist) — engine 0.17.0"
	},
	{
		"id": "Q17",
		"source": "quirk",
		"severity": null,
		"title": "Incremental shortfalls don't add up",
		"status": "Decided (simulated CMA-assessor recommendation, 2026-09-24; pending the real assessor and hydrologist) — engine 0.17.0"
	},
	{
		"id": "Q18",
		"source": "quirk",
		"severity": null,
		"title": "Several transfers from one dam",
		"status": "Decided (persona recommendation, 2026-09-24; pending the hydrologist) — engine 0.16.0"
	}
];
