// GENERATED by `pnpm gen:liability` from docs/engine-audit.md. Do not edit:
// change the audit item, then regenerate (limitations.test.ts checks it).
import type { Limitation } from './limitations';

export const KNOWN_LIMITATIONS: readonly Limitation[] = [
	{
		"id": "N1",
		"source": "finding",
		"severity": "Medium",
		"title": "Irrigation efficiency and return flow don't add up",
		"status": "Decided (persona recommendation, 2026-09-24; provisionally decided 2026-10-01 from the published practice, pending the client's hydrologist, issue #90) — engine 0.16.0"
	},
	{
		"id": "N2",
		"source": "finding",
		"severity": "High (dam-dominated farms)",
		"title": "Dam evaporation and seepage are ignored",
		"status": "Decided (persona recommendation, 2026-09-24; provisionally decided 2026-10-01 from the published practice, pending the client's hydrologist, issue #90) — engine 0.16.0"
	},
	{
		"id": "N3",
		"source": "finding",
		"severity": "Medium",
		"title": "Effective rain is applied day by day with no carry-over",
		"status": "Decided (persona recommendation, 2026-09-24; provisionally decided 2026-10-01 from the published practice, pending the client's hydrologist, issue #90), engine 0.14.0"
	},
	{
		"id": "N5",
		"source": "finding",
		"severity": "Medium (where boreholes pump near the river)",
		"title": "Groundwater was not modelled",
		"status": "Built (engine 0.23.0, roadmap WP-1.34, migration 012), off by default; the method provisionally decided 2026-10-01 from the published practice, pending the client's hydrologist (issue #90); its values need client data"
	},
	{
		"id": "N4",
		"source": "finding",
		"severity": "Low",
		"title": "Transfers ignore the receiving dam's free space, and the source's irrigation comes second",
		"status": "Decided (persona recommendation, 2026-09-24; provisionally decided 2026-10-01 from the published practice, pending the client's hydrologist, issue #90) — engine 0.16.0"
	},
	{
		"id": "N6",
		"source": "finding",
		"severity": "Medium (a dam with two or more transfer rules of one priority at different reserves, counting a rule active that month at rate 0); none on the client catchment (one rule) or the examples (bit-identical)",
		"title": "A transfer rule that moves nothing relaxed its siblings' reserve",
		"status": "Fixed, engine 1.36.0 (ER-11); how a band is shared decided pending the hydrologist (with N4)"
	},
	{
		"id": "B2",
		"source": "finding",
		"severity": "High (catchments whose rain record has gaps exported as zeros)",
		"title": "Missing catchment rain recorded as 0 runs the catchment dry",
		"status": "Fixed, engine 0.15.0 (CR-20, issue #2; operator decision 2026-09-24; provisional decision 2026-10-01 keeps the default; which runs are real is pending the client's station records)"
	},
	{
		"id": "B3",
		"source": "finding",
		"severity": "Medium (catchments whose rain network changed over the record)",
		"title": "The CHIRPS factors blend eras that disagree",
		"status": "Warned, engine 0.18.0 (CR-20)"
	},
	{
		"id": "S1",
		"source": "finding",
		"severity": "Medium (dams with a sediment rate over a long record; units coming in part-way through one)",
		"title": "A dam's capacity and a unit's abstraction now change over a run, on judgement calls the hydrologist hasn't made",
		"status": "Built; provisionally decided 2026-10-01 from the published practice, pending the client's hydrologist (issue #90): linear, run back to the in-service date (engine 1.63.0 asks for it), dead storage and the triggers scaled, the full-supply area kept"
	},
	{
		"id": "C2",
		"source": "finding",
		"severity": "Medium (fits on records with suspect days, or a gauged range entered)",
		"title": "Automatic calibration scored every observed day as recorded",
		"status": "Fixed, engine 1.22.0 (issue #66; provisional decision 2026-10-01 keeps the defaults, the hydrologist's confirmation pending; zero-flow stretches changed in engine 1.62.0, C3)"
	},
	{
		"id": "C3",
		"source": "finding",
		"severity": "Medium (fits on records of rivers that stop for 90 days or more)",
		"title": "A long stretch of zero flow was suspect, so the fit never saw the river dry",
		"status": "Fixed, engine 1.62.0 (provisional decision 2026-10-01, the client's hydrologist's confirmation pending; calibration-research.md § Provisional decisions)"
	},
	{
		"id": "A1",
		"source": "finding",
		"severity": "Medium (Reserve rule-table sites whose natural flow falls below the table's driest point: (100 − P_last) % of months with the percentile from the run, 1 % at the DRM's 99 % point; more with the gazette's curve when the model runs drier)",
		"title": "Below a rule table's driest point the requirement is scaled down with the flow, not held at the drought flow",
		"status": "Decided (from the literature, engine 0.21.0; provisional decision 2026-10-01 keeps it; the hydrologist's confirmation pending)"
	},
	{
		"id": "A2",
		"source": "finding",
		"severity": "Low",
		"title": "A rule table is interpolated linearly between its % points; Sawunyama & Hughes (2010) interpolate on a log scale",
		"status": "Decided (from the literature, engine 0.21.0; provisional decision 2026-10-01 keeps it; the hydrologist's confirmation pending)"
	},
	{
		"id": "A3",
		"source": "finding",
		"severity": "Medium (sites whose modelled natural flow differs from the determination's)",
		"title": "By default a month's natural percentile comes from the run's own natural flow, not the gazette's natural curve",
		"status": "Decided (from the literature and the persona drafts, engines 0.21.0 and 1.11.0; provisional decision 2026-10-01 keeps it; the hydrologist's confirmation pending)"
	},
	{
		"id": "A4",
		"source": "finding",
		"severity": "Medium (sites with a Reserve rule table)",
		"title": "The daily EWR charge, curtailment and the water account follow the pragmatic EWR by default, while the Reserve compliance report follows the rule table",
		"status": "Built (engine 1.3.0, issue #64), off by default; provisional decision 2026-10-01 keeps it; the hydrologist's or the assessor's confirmation pending"
	},
	{
		"id": "A5",
		"source": "finding",
		"severity": "Medium (sites with a low-flow requirement and floods in dry months)",
		"title": "By default a low-flow requirement is judged on the month's total volume, so a flood month can pass its low flows while its base flow was short",
		"status": "Built (engines 1.3.0 and 1.6.0, issue #64), off by default; provisional decision 2026-10-01 keeps it; the hydrologist's confirmation pending"
	},
	{
		"id": "A6",
		"source": "finding",
		"severity": "Medium (rule tables with high-flow components)",
		"title": "A high-flow event is found in daily flow by the engine's own rule: at least half the duration at or above half the peak",
		"status": "Decided (engine 1.9.0, licensing-authority persona review of issue #46; provisional decision 2026-10-01 keeps it; the hydrologist's confirmation pending)"
	},
	{
		"id": "A7",
		"source": "finding",
		"severity": "Medium (rule tables with high-flow components)",
		"title": "A year is asked for no more high-flow events than its natural flow had, counted per water year, and the DRM's high-flow volumes are not checked",
		"status": "Decided (from the literature, engine 0.33.0; provisional decision 2026-10-01 keeps it; the hydrologist's confirmation pending)"
	},
	{
		"id": "L1",
		"source": "finding",
		"severity": "Medium (licence applications that insert a senior other water user on a reach)",
		"title": "A new senior water user inserted above existing farms is classed as a changed assumption, not the applicant's proposal",
		"status": "Decided (conservative, engine 1.35.0; Needs hydrologist)"
	},
	{
		"id": "L2",
		"source": "finding",
		"severity": "Medium (capped runs whose licences state months of use or a maximum rate)",
		"title": "The cap applies a licence's months of use and maximum rate to every surface draw, the farm's own dam included, never to water going into the dam, and not at all while no licence of the source is in force",
		"status": "Needs hydrologist (engine 1.37.0, issue #72, #90)"
	},
	{
		"id": "W1",
		"source": "finding",
		"severity": "Medium (full-allocation runs of a unit with a domestic or municipal demand object whose registered volume is below its demand)",
		"title": "A full allocation rescales a domestic or municipal object below its basic-needs floor unless a restriction is in force that day",
		"status": "Needs hydrologist (engine 1.44.0, issue #123)"
	},
	{
		"id": "Q3",
		"source": "quirk",
		"severity": null,
		"title": "Transfer order / spill at the receiver",
		"status": "Decided (persona recommendation, 2026-09-24; provisionally decided 2026-10-01 from the published practice, pending the client's hydrologist, issue #90) — engine 0.16.0"
	},
	{
		"id": "Q5",
		"source": "quirk",
		"severity": null,
		"title": "Irrigation may empty the dam",
		"status": "Decided (persona recommendation, 2026-09-24; provisionally decided 2026-10-01 from the published practice, pending the client's hydrologist, issue #90; which dams keep a reserve is client data) — engine 0.16.0"
	},
	{
		"id": "Q6",
		"source": "quirk",
		"severity": null,
		"title": "Threshold on the demand offset",
		"status": "The larger issue, no carry-over, is N3: decided on a persona recommendation (engine 0.14.0, soil-water store), pending the hydrologist"
	},
	{
		"id": "Q11",
		"source": "quirk",
		"severity": null,
		"title": "Equitable target ignores the network",
		"status": "Decided (simulated CMA-assessor recommendation, 2026-09-24; pending the real assessor and hydrologist) — engine 0.17.0, labels only"
	},
	{
		"id": "Q13",
		"source": "quirk",
		"severity": null,
		"title": "EWR cut on a farm with no demand",
		"status": "Decided (simulated CMA-assessor recommendation, 2026-09-24; pending the real assessor and hydrologist) — engine 0.17.0"
	},
	{
		"id": "Q17",
		"source": "quirk",
		"severity": null,
		"title": "Incremental shortfalls don't add up",
		"status": "Decided (simulated CMA-assessor recommendation, 2026-09-24; pending the real assessor and hydrologist) — engine 0.17.0"
	},
	{
		"id": "Q18",
		"source": "quirk",
		"severity": null,
		"title": "Several transfers from one dam",
		"status": "Decided (persona recommendation, 2026-09-24; provisionally decided 2026-10-01 from the published practice, pending the client's hydrologist, issue #90) — engine 0.16.0"
	}
];
