// GENERATED by `pnpm gen:liability` from docs/methodology/v<N>.md. Do not edit:
// add a new version, then regenerate (methodology.test.ts checks it).
import type { MethodologyVersion } from './methodology';

/** Every published version, oldest first. */
export const METHODOLOGY_VERSIONS: readonly MethodologyVersion[] = [
	{
		"version": "methodology-1",
		"file": "v1.md",
		"sha256": "e92bd23d5f99fdedb86142c38bff2b446189c03195c765df187d6f914fc62d1e"
	}
];

/** The current version: new sign-offs and evidence packs cite it. */
export const METHODOLOGY: MethodologyVersion = METHODOLOGY_VERSIONS[0]!;
