// GENERATED by `pnpm gen:liability` from docs/methodology/v<N>.md. Do not edit:
// add a new version, then regenerate (methodology.test.ts checks it).
import type { MethodologyVersion } from './methodology';

/** Every published version, oldest first. */
export const METHODOLOGY_VERSIONS: readonly MethodologyVersion[] = [
	{
		"version": "methodology-1",
		"file": "v1.md",
		"sha256": "8f26d0e2f723b302a0a499f6072db8c3c6ad35f4d12dc90f1501a2357cfcad88"
	},
	{
		"version": "methodology-2",
		"file": "v2.md",
		"sha256": "4e342a3cf5a7636f469aeec76aa41d06e8dda765ef9e2c3f10062f0342095370"
	},
	{
		"version": "methodology-3",
		"file": "v3.md",
		"sha256": "bab17f104f6c20bf4ba4bfa4936b681b13066b39e77e4fe82f483b13a989b4b9"
	},
	{
		"version": "methodology-4",
		"file": "v4.md",
		"sha256": "7cd4583826ab33421e9889337dd09da333375cecddca1848d2be82bb9480083b"
	}
];

/** The current version: new sign-offs and evidence packs cite it. */
export const METHODOLOGY: MethodologyVersion = METHODOLOGY_VERSIONS[3]!;
