// Generated by `pnpm gen:landing-art` (bin/gen-landing-art.sh, scripts/landing-art/modules.mjs).
// Don't edit by hand: change the sources in scripts/landing-art/ and rerun it.
// The hero render's size and blurred placeholders, where the scene's rivers,
// dams, clouds and gauge fall in it (% of the picture), each framed app
// screen's size, the icons' and river divider's path data, and the contour
// texture's size.
/* eslint-disable */
export const ART = {
	"hero": {
		"width": 1600,
		"height": 1302,
		"widths": [
			800,
			1200,
			1600
		],
		"placeholder": {
			"day": "data:image/webp;base64,UklGRoYBAABXRUJQVlA4WAoAAAAQAAAAFwAAEwAAQUxQSNMAAAABkHPbtrHnmk8q23ZS2bZT2bZt2yyd1mhZ27Zt4+NpHkXEBAAxZ6I4MOv6Wuysy87Jy0aHbRD/vo2rOsVW8gIIGLKS+X4j4tNwc6Wvo42I34YCifU+En9fvm7nK4WqRakAgHTtDVI9ym45Pf4VDuC0hDT/I+KDIVvaPTI5L2T/gox2s+jcMhMHAtOMvBsDmI3+YWBTFAB4Ijdp/U4GQrn6exqtbETAYjLyi8qkKFDkCFwm29ME6pJlVwTPLkBbt+cL8U8WMMjqMfWvk50JAMkkOSAGAFZQOCCMAAAAUAUAnQEqGAAUAD7tYqtPqaUjojAYCAEwHYlmAL15IAGBprKJjlvMK/wUKOoNtQr8CE/AAP3MHnX0SrCboditheg8H6Ra/kVqfBhGre7Ho104TF91CMABZjubSMBQNuYfDnG5ax6KJM06CloQu66M6j41tf9mKHX9648KHEMAtsGpq+VPaB5LQEgAAAA=",
			"dusk": "data:image/webp;base64,UklGRmwBAABXRUJQVlA4WAoAAAAQAAAAFwAAEwAAQUxQSNMAAAABkHPbtrHnmk8q23ZS2bZT2bZt2yyd1mhZ27Zt4+NpHkXEBAAxZ6I4MOv6Wuysy87Jy0aHbRD/vo2rOsVW8gIIGLKS+X4j4tNwc6Wvo42I34YCifU+En9fvm7nK4WqRakAgHTtDVI9ym45Pf4VDuC0hDT/I+KDIVvaPTI5L2T/gox2s+jcMhMHAtOMvBsDmI3+YWBTFAB4Ijdp/U4GQrn6exqtbETAYjLyi8qkKFDkCFwm29ME6pJlVwTPLkBbt+cL8U8WMMjqMfWvk50JAMkkOSAGAFZQOCByAAAAsAQAnQEqGAAUAD7tZKpNqaWkIjAIATAdiUAWHYQ8AW2hQTfSkwXAHTnXzajLAAD+y0tGAFJjHKGgasSWJUajd4Jaxfe1OKSL+1InaEcJ89Wbk5lb5k7hrD3mbHb1qA/JXGXM/dpeBNgY6B0ZL4MFlvAA"
		}
	},
	"overlay": {
		"width": 1600,
		"height": 1303,
		"river": [
			[
				62.63,
				21.86
			],
			[
				62.42,
				22.88
			],
			[
				62.15,
				24.64
			],
			[
				61.95,
				25.07
			],
			[
				61.71,
				25.72
			],
			[
				61.36,
				27.69
			],
			[
				61.08,
				28.28
			],
			[
				60.75,
				29.44
			],
			[
				60.38,
				30.68
			],
			[
				60.01,
				31.56
			],
			[
				59.57,
				33.29
			],
			[
				59.11,
				34.82
			],
			[
				58.64,
				36.15
			],
			[
				58.15,
				37.45
			],
			[
				57.64,
				38.7
			],
			[
				57.12,
				39.5
			],
			[
				56.58,
				40.31
			],
			[
				56,
				41.37
			],
			[
				55.4,
				42.31
			],
			[
				54.79,
				42.91
			],
			[
				54.14,
				43.95
			],
			[
				53.49,
				44.56
			],
			[
				52.81,
				45.23
			],
			[
				52.12,
				45.54
			],
			[
				51.42,
				45.76
			],
			[
				50.69,
				46.02
			],
			[
				49.94,
				46.27
			],
			[
				49.17,
				46.57
			],
			[
				48.39,
				47.24
			],
			[
				47.59,
				47.66
			],
			[
				46.79,
				47.96
			],
			[
				45.97,
				48.02
			],
			[
				45.14,
				48.32
			],
			[
				44.31,
				48.69
			],
			[
				43.47,
				49.36
			],
			[
				42.63,
				49.96
			],
			[
				41.79,
				50.64
			],
			[
				40.95,
				50.98
			],
			[
				40.11,
				51.46
			],
			[
				39.27,
				51.91
			],
			[
				38.43,
				52.1
			],
			[
				37.61,
				52.73
			],
			[
				36.8,
				53.38
			],
			[
				36,
				54.06
			],
			[
				35.21,
				54.74
			],
			[
				34.42,
				55.23
			],
			[
				33.64,
				55.55
			],
			[
				32.88,
				56.05
			],
			[
				32.12,
				56.42
			],
			[
				31.37,
				56.81
			],
			[
				30.66,
				57.5
			],
			[
				29.97,
				58.17
			],
			[
				29.28,
				58.66
			],
			[
				28.6,
				59.13
			],
			[
				27.94,
				59.73
			],
			[
				27.3,
				60.23
			],
			[
				26.7,
				61.08
			],
			[
				26.07,
				61.33
			],
			[
				25.5,
				62.15
			],
			[
				24.92,
				62.75
			]
		],
		"tributary": [
			[
				41,
				9.76
			],
			[
				41.11,
				9.63
			],
			[
				41.27,
				11.96
			],
			[
				41.42,
				13.42
			],
			[
				41.59,
				16.05
			],
			[
				41.75,
				17.36
			],
			[
				41.9,
				18.05
			],
			[
				42.06,
				19.06
			],
			[
				42.24,
				20.62
			],
			[
				42.41,
				21.45
			],
			[
				42.62,
				24.08
			],
			[
				42.83,
				27.05
			],
			[
				43.03,
				27.91
			],
			[
				43.23,
				28.67
			],
			[
				43.45,
				29.33
			],
			[
				43.67,
				30.11
			],
			[
				43.92,
				31.91
			],
			[
				44.17,
				32.94
			],
			[
				44.44,
				34.43
			],
			[
				44.72,
				35.38
			],
			[
				45.02,
				36.82
			],
			[
				45.34,
				38.13
			],
			[
				45.68,
				39.61
			],
			[
				46.04,
				40.54
			],
			[
				46.44,
				42.04
			],
			[
				46.88,
				42.76
			],
			[
				47.37,
				43.59
			],
			[
				47.94,
				44.22
			],
			[
				48.64,
				44.79
			],
			[
				49.73,
				46.49
			]
		],
		"dams": {
			"left": [
				[
					46.49,
					30.44
				],
				[
					46.76,
					30.16
				],
				[
					46.92,
					29.85
				],
				[
					46.94,
					29.5
				],
				[
					46.82,
					29.13
				],
				[
					46.59,
					28.75
				],
				[
					46.23,
					28.37
				],
				[
					45.78,
					28.01
				],
				[
					45.23,
					27.67
				],
				[
					44.61,
					27.36
				],
				[
					43.93,
					27.1
				],
				[
					43.22,
					26.89
				],
				[
					42.5,
					26.73
				],
				[
					41.78,
					26.64
				],
				[
					41.09,
					26.6
				],
				[
					40.45,
					26.63
				],
				[
					39.87,
					26.72
				],
				[
					39.38,
					26.88
				],
				[
					38.98,
					27.08
				],
				[
					38.68,
					27.34
				],
				[
					38.51,
					27.64
				],
				[
					38.46,
					27.98
				],
				[
					38.53,
					28.34
				],
				[
					38.74,
					28.71
				],
				[
					39.06,
					29.09
				],
				[
					39.5,
					29.47
				],
				[
					40.03,
					29.82
				],
				[
					40.65,
					30.14
				],
				[
					41.34,
					30.42
				],
				[
					42.08,
					30.65
				],
				[
					42.83,
					30.82
				],
				[
					43.58,
					30.92
				],
				[
					44.31,
					30.96
				],
				[
					44.98,
					30.93
				],
				[
					45.58,
					30.83
				],
				[
					46.09,
					30.66
				]
			],
			"right": [
				[
					67.26,
					55.76
				],
				[
					67.53,
					55.34
				],
				[
					67.64,
					54.85
				],
				[
					67.59,
					54.32
				],
				[
					67.38,
					53.77
				],
				[
					67.03,
					53.2
				],
				[
					66.54,
					52.64
				],
				[
					65.94,
					52.11
				],
				[
					65.23,
					51.62
				],
				[
					64.45,
					51.18
				],
				[
					63.61,
					50.8
				],
				[
					62.75,
					50.5
				],
				[
					61.88,
					50.29
				],
				[
					61.03,
					50.16
				],
				[
					60.22,
					50.12
				],
				[
					59.48,
					50.18
				],
				[
					58.83,
					50.33
				],
				[
					58.28,
					50.57
				],
				[
					57.85,
					50.89
				],
				[
					57.56,
					51.28
				],
				[
					57.41,
					51.74
				],
				[
					57.42,
					52.24
				],
				[
					57.57,
					52.79
				],
				[
					57.88,
					53.35
				],
				[
					58.33,
					53.91
				],
				[
					58.91,
					54.46
				],
				[
					59.6,
					54.98
				],
				[
					60.39,
					55.45
				],
				[
					61.25,
					55.86
				],
				[
					62.15,
					56.19
				],
				[
					63.07,
					56.43
				],
				[
					63.97,
					56.57
				],
				[
					64.82,
					56.61
				],
				[
					65.6,
					56.54
				],
				[
					66.28,
					56.37
				],
				[
					66.84,
					56.11
				]
			]
		},
		"clouds": [
			[
				46.88,
				10.78
			],
			[
				61.94,
				13.14
			],
			[
				73.03,
				21.89
			]
		],
		"ridges": [
			[
				46.84,
				20
			],
			[
				61.23,
				25.22
			],
			[
				71.8,
				33.92
			]
		],
		"sun": [
			84.74,
			17.67
		],
		"gauge": [
			30.35,
			58.4
		],
		"outlet": [
			27.39,
			59.71
		],
		"reach": [
			[
				40.37,
				51.21
			],
			[
				39,
				51.94
			],
			[
				37.64,
				52.71
			],
			[
				36.32,
				53.8
			],
			[
				35.02,
				54.94
			],
			[
				33.73,
				55.48
			],
			[
				32.48,
				56.28
			],
			[
				31.26,
				56.9
			],
			[
				30.11,
				58.05
			],
			[
				28.98,
				58.88
			],
			[
				27.89,
				59.79
			],
			[
				26.87,
				60.86
			],
			[
				25.85,
				61.51
			],
			[
				24.92,
				62.75
			]
		],
		"farms": {
			"orchard": [
				30.21,
				35.54
			],
			"vineyard": [
				55.46,
				61.61
			]
		},
		"slopes": [
			[
				38.8,
				11.69
			],
			[
				81.68,
				35.45
			],
			[
				52.02,
				24.06
			]
		]
	},
	"screens": {
		"laptop": {
			"width": 1600,
			"height": 1036
		},
		"phone": {
			"width": 434,
			"height": 888
		},
		"network": {
			"width": 1280,
			"height": 800
		},
		"river": {
			"width": 1280,
			"height": 800
		}
	},
	"icons": {
		"hydrologist": [
			{
				"d": "M8 7 V40 H42",
				"accent": false
			},
			{
				"d": "M8 29 H42",
				"accent": false,
				"dash": "3 3"
			},
			{
				"d": "M8 36 C13 36 15 13 19.5 13 C24 13 25 30 31 32.5 C35 34 38 34 42 34.5",
				"accent": true
			}
		],
		"association": [
			{
				"d": "M13.5 13.5 L22 23 M34.5 13.5 L26 23 M10.5 30 L21.5 26 M24 28 V36",
				"accent": false
			},
			{
				"d": "M 14.5,11 A 3.5,3.5 0 0 1 11,14.5 3.5,3.5 0 0 1 7.5,11 3.5,3.5 0 0 1 11,7.5 3.5,3.5 0 0 1 14.5,11 Z",
				"accent": false
			},
			{
				"d": "M 40.5,11 A 3.5,3.5 0 0 1 37,14.5 3.5,3.5 0 0 1 33.5,11 3.5,3.5 0 0 1 37,7.5 3.5,3.5 0 0 1 40.5,11 Z",
				"accent": false
			},
			{
				"d": "M 10.5,31 A 3.5,3.5 0 0 1 7,34.5 3.5,3.5 0 0 1 3.5,31 3.5,3.5 0 0 1 7,27.5 3.5,3.5 0 0 1 10.5,31 Z",
				"accent": false
			},
			{
				"d": "m 27,25.5 a 3,3 0 0 1 -3,3 3,3 0 0 1 -3,-3 3,3 0 0 1 3,-3 3,3 0 0 1 3,3 z",
				"accent": false
			},
			{
				"d": "m 28,40 a 4,4 0 0 1 -4,4 4,4 0 0 1 -4,-4 4,4 0 0 1 4,-4 4,4 0 0 1 4,4 z",
				"accent": true
			}
		],
		"licensing": [
			{
				"d": "M11 5 H29 L37 13 V43 H11 Z",
				"accent": false
			},
			{
				"d": "M29 5 V13 H37",
				"accent": false
			},
			{
				"d": "M15.5 22 C18.5 18.5 21 25.5 24 22 S29.5 18.5 32.5 22",
				"accent": true
			},
			{
				"d": "M15.5 29 H26",
				"accent": false
			},
			{
				"d": "m 33,35 a 4,4 0 0 1 -4,4 4,4 0 0 1 -4,-4 4,4 0 0 1 4,-4 4,4 0 0 1 4,4 z",
				"accent": false
			},
			{
				"d": "M26.5 38 L25.5 43 L29 41.5 L32.5 43 L31.5 38",
				"accent": false
			}
		],
		"farmer": [
			{
				"d": "m 16.5,4 h 15 C 33.439,4 35,5.561 35,7.5 v 33 c 0,1.939 -1.561,3.5 -3.5,3.5 h -15 C 14.561,44 13,42.439 13,40.5 V 7.5 C 13,5.561 14.561,4 16.5,4 Z",
				"accent": false
			},
			{
				"d": "M21.5 8 H26.5",
				"accent": false
			},
			{
				"d": "M17 26 A7 7 0 0 1 31 26",
				"accent": false
			},
			{
				"d": "M24 26 L28.5 20.5",
				"accent": true
			},
			{
				"d": "M17 33 C19 31.8 21 34.2 24 33 S29 31.8 31 33 M17 37.5 C19 36.3 21 38.7 24 37.5 S29 36.3 31 37.5",
				"accent": true
			}
		]
	},
	"river": "M0 14 C60 14 80 5 140 6 S230 22 300 21 S390 4 470 6 S560 23 640 22 S740 5 820 7 S920 21 1000 20 S1110 9 1200 12",
	"contours": {
		"width": 1500,
		"height": 997
	}
};
