// Generated by `pnpm gen:landing-art` (backend/scripts/landing-data.ts): the engine
// run on the invented Kleinberg example catchment. Don't edit by hand; rerun it.
/* eslint-disable */
export const DATA = {
	"source": "Invented example catchment (Kleinberg); every figure is synthetic.",
	"engineVersion": "1.15.0",
	"period": {
		"start": "2010-01-01",
		"end": "2024-12-31"
	},
	"hero": {
		"reserveMetPct": 41.6,
		"farms": 4,
		"dams": 4,
		"years": 15,
		"days": 5479,
		"calibrationNse": 0.87
	},
	"story": {
		"waterYear": "2012/13",
		"rain": [
			7.2,
			14.4,
			19.6,
			5.5,
			7.3,
			11.6,
			0,
			0,
			0,
			1.2,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			2.2,
			7.1,
			22.2,
			0,
			20,
			0,
			16.6,
			4.3,
			70,
			23.3,
			30.8,
			58,
			29.1,
			87.9,
			34.8,
			88.3,
			66.6,
			27,
			30.9,
			88.5,
			43,
			22.9,
			25.1,
			15.2,
			61,
			33.5,
			24.2,
			35.1,
			2.5,
			43.5
		],
		"runoff": [
			1.873,
			1.094,
			0.793,
			0.657,
			0.43,
			0.319,
			0.234,
			0.177,
			0.139,
			0.112,
			0.092,
			0.078,
			0.067,
			0.058,
			0.052,
			0.046,
			0.042,
			0.038,
			0.035,
			0.032,
			0.03,
			0.027,
			0.026,
			0.024,
			0.023,
			0.022,
			0.021,
			0.02,
			0.019,
			0.02,
			0.031,
			0.054,
			0.067,
			0.139,
			0.263,
			0.725,
			1.96,
			2.231,
			5.381,
			3.657,
			1.852,
			5.537,
			5.795,
			2.251,
			1.633,
			2.132,
			4.195,
			3.233,
			2.287,
			2.554,
			1.052,
			1.671
		],
		"dam": {
			"name": "Rooikloof",
			"pctFull": [
				100,
				100,
				100,
				100,
				100,
				100,
				100,
				100,
				100,
				99.4,
				98.1,
				96.3,
				94.1,
				91.4,
				88.1,
				84.5,
				80.9,
				77.2,
				73.9,
				70.5,
				67.1,
				63.8,
				61.6,
				59.7,
				58.9,
				57.1,
				56,
				56.2,
				55.7,
				55.9,
				56.4,
				58.5,
				60.3,
				63.8,
				70.8,
				82.1,
				99.5,
				100,
				100,
				100,
				100,
				100,
				100,
				100,
				100,
				100,
				100,
				100,
				100,
				100,
				100,
				100
			]
		},
		"farm": {
			"name": "Rustenvrede",
			"demand": [
				0,
				1526,
				1356,
				2357,
				2942,
				3263,
				3994,
				3994,
				4195,
				4696,
				4696,
				4696,
				4696,
				4857,
				4884,
				4884,
				4884,
				4609,
				4242,
				4242,
				4242,
				3748,
				2935,
				2587,
				1515,
				3091,
				1035,
				1168,
				1553,
				587,
				361,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				105,
				0
			],
			"supplied": [
				0,
				1526,
				1356,
				2357,
				2942,
				3263,
				3994,
				3994,
				4195,
				4696,
				4696,
				4696,
				4696,
				4857,
				4884,
				4884,
				4884,
				976,
				595,
				498,
				454,
				424,
				407,
				388,
				413,
				326,
				191,
				506,
				272,
				389,
				89,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				105,
				0
			]
		},
		"river": {
			"flow": [
				1.863,
				1.071,
				0.775,
				0.608,
				0.328,
				0.198,
				0.077,
				0.02,
				0.002,
				0.002,
				0.002,
				0.002,
				0.002,
				0.003,
				0.003,
				0.003,
				0.003,
				0.001,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0.057,
				1.661,
				2.27,
				5.409,
				3.666,
				1.863,
				5.576,
				5.812,
				2.257,
				1.639,
				2.134,
				4.219,
				3.243,
				2.29,
				2.562,
				1.043,
				1.683
			],
			"reserve": [
				0.291,
				0.291,
				0.291,
				0.291,
				0.175,
				0.088,
				0.088,
				0.088,
				0.07,
				0.027,
				0.027,
				0.027,
				0.027,
				0.016,
				0.014,
				0.014,
				0.014,
				0.012,
				0.009,
				0.009,
				0.009,
				0.008,
				0.007,
				0.007,
				0.007,
				0.007,
				0.008,
				0.008,
				0.008,
				0.008,
				0.032,
				0.042,
				0.042,
				0.042,
				0.212,
				0.637,
				0.637,
				0.637,
				0.637,
				1.37,
				1.37,
				1.37,
				1.37,
				1.447,
				1.505,
				1.505,
				1.505,
				1.398,
				0.756,
				0.756,
				0.756,
				0.756
			],
			"weeksBelow": 30
		}
	},
	"whatIf": {
		"farm": "Bergwater",
		"baseHa": 60,
		"baseDamM3": 400000,
		"baseSupplied": 79.7,
		"extraHa": [
			0,
			10,
			20,
			30,
			40,
			50,
			60
		],
		"damScale": [
			1,
			1.25,
			1.5,
			1.75,
			2
		],
		"grid": [
			[
				{
					"reserveDays": 213.4,
					"supplied": 79.7,
					"suppliedKm3": 608
				},
				{
					"reserveDays": 214.1,
					"supplied": 89.2,
					"suppliedKm3": 681
				},
				{
					"reserveDays": 214.6,
					"supplied": 97.1,
					"suppliedKm3": 741
				},
				{
					"reserveDays": 215,
					"supplied": 99.2,
					"suppliedKm3": 757
				},
				{
					"reserveDays": 215.1,
					"supplied": 99.6,
					"suppliedKm3": 760
				}
			],
			[
				{
					"reserveDays": 214,
					"supplied": 72.6,
					"suppliedKm3": 627
				},
				{
					"reserveDays": 214.8,
					"supplied": 81,
					"suppliedKm3": 701
				},
				{
					"reserveDays": 215.1,
					"supplied": 89.4,
					"suppliedKm3": 773
				},
				{
					"reserveDays": 215.9,
					"supplied": 96.6,
					"suppliedKm3": 835
				},
				{
					"reserveDays": 216.1,
					"supplied": 99.1,
					"suppliedKm3": 856
				}
			],
			[
				{
					"reserveDays": 214.9,
					"supplied": 66.8,
					"suppliedKm3": 646
				},
				{
					"reserveDays": 215.5,
					"supplied": 74.5,
					"suppliedKm3": 719
				},
				{
					"reserveDays": 216.1,
					"supplied": 82,
					"suppliedKm3": 792
				},
				{
					"reserveDays": 216.7,
					"supplied": 89.4,
					"suppliedKm3": 864
				},
				{
					"reserveDays": 217.1,
					"supplied": 96,
					"suppliedKm3": 928
				}
			],
			[
				{
					"reserveDays": 215.5,
					"supplied": 62.1,
					"suppliedKm3": 663
				},
				{
					"reserveDays": 216.3,
					"supplied": 69.1,
					"suppliedKm3": 737
				},
				{
					"reserveDays": 216.7,
					"supplied": 75.9,
					"suppliedKm3": 811
				},
				{
					"reserveDays": 217.5,
					"supplied": 82.7,
					"suppliedKm3": 883
				},
				{
					"reserveDays": 217.9,
					"supplied": 89.4,
					"suppliedKm3": 955
				}
			],
			[
				{
					"reserveDays": 216.2,
					"supplied": 58.1,
					"suppliedKm3": 680
				},
				{
					"reserveDays": 216.9,
					"supplied": 64.5,
					"suppliedKm3": 754
				},
				{
					"reserveDays": 217.4,
					"supplied": 70.8,
					"suppliedKm3": 828
				},
				{
					"reserveDays": 218,
					"supplied": 77,
					"suppliedKm3": 900
				},
				{
					"reserveDays": 218.5,
					"supplied": 83.2,
					"suppliedKm3": 973
				}
			],
			[
				{
					"reserveDays": 216.8,
					"supplied": 54.7,
					"suppliedKm3": 695
				},
				{
					"reserveDays": 217.7,
					"supplied": 60.6,
					"suppliedKm3": 770
				},
				{
					"reserveDays": 217.9,
					"supplied": 66.4,
					"suppliedKm3": 844
				},
				{
					"reserveDays": 218.7,
					"supplied": 72.2,
					"suppliedKm3": 917
				},
				{
					"reserveDays": 218.9,
					"supplied": 77.9,
					"suppliedKm3": 990
				}
			],
			[
				{
					"reserveDays": 217.3,
					"supplied": 51.8,
					"suppliedKm3": 710
				},
				{
					"reserveDays": 218.1,
					"supplied": 57.2,
					"suppliedKm3": 785
				},
				{
					"reserveDays": 218.3,
					"supplied": 62.6,
					"suppliedKm3": 859
				},
				{
					"reserveDays": 219.1,
					"supplied": 68,
					"suppliedKm3": 933
				},
				{
					"reserveDays": 219.5,
					"supplied": 73.3,
					"suppliedKm3": 1006
				}
			]
		]
	}
};
