// Generated by `pnpm gen:landing-art` (backend/scripts/landing-data.ts): the engine
// run on the invented Kleinberg example catchment. Don't edit by hand; rerun it.
/* eslint-disable */
export const DATA = {
	"source": "Invented example catchment (Kleinberg); every figure is synthetic.",
	"engineVersion": "1.23.0",
	"period": {
		"start": "2010-01-01",
		"end": "2024-12-31"
	},
	"hero": {
		"reserveNotMetPct": 58.5,
		"farms": 4,
		"dams": 4,
		"years": 15,
		"days": 5479,
		"calibrationNse": 0.87
	},
	"story": {
		"waterYear": "2012/13",
		"rain": [
			7.2,
			14.4,
			19.6,
			5.5,
			7.3,
			11.6,
			0,
			0,
			0,
			1.2,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			2.2,
			7.1,
			22.2,
			0,
			20,
			0,
			16.6,
			4.3,
			70,
			23.3,
			30.8,
			58,
			29.1,
			87.9,
			34.8,
			88.3,
			66.6,
			27,
			30.9,
			88.5,
			43,
			22.9,
			25.1,
			15.2,
			61,
			33.5,
			24.2,
			35.1,
			2.5,
			43.5
		],
		"runoff": [
			1.873,
			1.094,
			0.793,
			0.657,
			0.43,
			0.319,
			0.234,
			0.177,
			0.139,
			0.112,
			0.092,
			0.078,
			0.067,
			0.058,
			0.052,
			0.046,
			0.042,
			0.038,
			0.035,
			0.032,
			0.03,
			0.027,
			0.026,
			0.024,
			0.023,
			0.022,
			0.021,
			0.02,
			0.019,
			0.02,
			0.031,
			0.054,
			0.067,
			0.139,
			0.263,
			0.725,
			1.96,
			2.231,
			5.381,
			3.657,
			1.852,
			5.537,
			5.795,
			2.251,
			1.633,
			2.132,
			4.195,
			3.233,
			2.287,
			2.554,
			1.052,
			1.671
		],
		"dam": {
			"name": "Rooikloof",
			"pctFull": [
				100,
				100,
				100,
				100,
				100,
				100,
				100,
				100,
				100,
				99.3,
				97.9,
				95.9,
				93.6,
				90.7,
				87.2,
				83.6,
				79.8,
				75.9,
				72.5,
				69,
				65.4,
				62,
				59.7,
				57.7,
				56.9,
				55,
				53.8,
				54,
				53.4,
				53.7,
				54.1,
				56.2,
				58,
				61.5,
				68.5,
				79.8,
				99.2,
				100,
				100,
				100,
				100,
				100,
				100,
				100,
				100,
				100,
				100,
				100,
				100,
				100,
				100,
				100
			]
		},
		"farm": {
			"name": "Rustenvrede",
			"demand": [
				0,
				1582,
				1405,
				2443,
				3049,
				3382,
				4140,
				4140,
				4348,
				4868,
				4868,
				4868,
				4868,
				5035,
				5063,
				5063,
				5063,
				4777,
				4397,
				4397,
				4397,
				3886,
				3042,
				2682,
				1570,
				3204,
				1073,
				1211,
				1610,
				608,
				375,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				108,
				0
			],
			"supplied": [
				0,
				1582,
				1405,
				2443,
				3049,
				3382,
				4140,
				4140,
				4348,
				4868,
				4868,
				4868,
				4868,
				5035,
				5063,
				5063,
				3723,
				778,
				606,
				499,
				455,
				425,
				407,
				389,
				414,
				327,
				191,
				506,
				272,
				389,
				89,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				108,
				0
			]
		},
		"river": {
			"flow": [
				1.863,
				1.071,
				0.774,
				0.607,
				0.327,
				0.196,
				0.076,
				0.019,
				0.003,
				0.003,
				0.003,
				0.003,
				0.003,
				0.003,
				0.003,
				0.003,
				0.002,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				0.057,
				1.638,
				2.27,
				5.409,
				3.666,
				1.863,
				5.576,
				5.812,
				2.257,
				1.639,
				2.134,
				4.219,
				3.243,
				2.29,
				2.562,
				1.043,
				1.683
			],
			"reserve": [
				0.291,
				0.291,
				0.291,
				0.291,
				0.175,
				0.088,
				0.088,
				0.088,
				0.07,
				0.027,
				0.027,
				0.027,
				0.027,
				0.016,
				0.014,
				0.014,
				0.014,
				0.012,
				0.009,
				0.009,
				0.009,
				0.008,
				0.007,
				0.007,
				0.007,
				0.007,
				0.008,
				0.008,
				0.008,
				0.008,
				0.032,
				0.042,
				0.042,
				0.042,
				0.212,
				0.637,
				0.637,
				0.637,
				0.637,
				1.37,
				1.37,
				1.37,
				1.37,
				1.447,
				1.505,
				1.505,
				1.505,
				1.398,
				0.756,
				0.756,
				0.756,
				0.756
			],
			"weeksBelow": 30
		}
	},
	"whatIf": {
		"farm": "Bergwater",
		"baseHa": 60,
		"baseDamM3": 400000,
		"baseSupplied": 80.1,
		"extraHa": [
			0,
			10,
			20,
			30,
			40,
			50,
			60
		],
		"damScale": [
			1,
			1.25,
			1.5,
			1.75,
			2
		],
		"grid": [
			[
				{
					"reserveDays": 213.7,
					"supplied": 80.1,
					"suppliedKm3": 611
				},
				{
					"reserveDays": 214.3,
					"supplied": 89.6,
					"suppliedKm3": 684
				},
				{
					"reserveDays": 214.8,
					"supplied": 97.3,
					"suppliedKm3": 742
				},
				{
					"reserveDays": 215.2,
					"supplied": 99.3,
					"suppliedKm3": 757
				},
				{
					"reserveDays": 215.3,
					"supplied": 99.6,
					"suppliedKm3": 760
				}
			],
			[
				{
					"reserveDays": 214.3,
					"supplied": 72.9,
					"suppliedKm3": 631
				},
				{
					"reserveDays": 214.9,
					"supplied": 81.4,
					"suppliedKm3": 704
				},
				{
					"reserveDays": 215.5,
					"supplied": 89.7,
					"suppliedKm3": 776
				},
				{
					"reserveDays": 216.2,
					"supplied": 96.8,
					"suppliedKm3": 837
				},
				{
					"reserveDays": 216.5,
					"supplied": 99.1,
					"suppliedKm3": 857
				}
			],
			[
				{
					"reserveDays": 215.2,
					"supplied": 67.2,
					"suppliedKm3": 649
				},
				{
					"reserveDays": 215.8,
					"supplied": 74.8,
					"suppliedKm3": 723
				},
				{
					"reserveDays": 216.3,
					"supplied": 82.3,
					"suppliedKm3": 795
				},
				{
					"reserveDays": 217,
					"supplied": 89.8,
					"suppliedKm3": 867
				},
				{
					"reserveDays": 217.3,
					"supplied": 96.3,
					"suppliedKm3": 930
				}
			],
			[
				{
					"reserveDays": 215.8,
					"supplied": 62.4,
					"suppliedKm3": 666
				},
				{
					"reserveDays": 216.5,
					"supplied": 69.4,
					"suppliedKm3": 740
				},
				{
					"reserveDays": 217.1,
					"supplied": 76.2,
					"suppliedKm3": 814
				},
				{
					"reserveDays": 217.7,
					"supplied": 83,
					"suppliedKm3": 886
				},
				{
					"reserveDays": 218,
					"supplied": 89.7,
					"suppliedKm3": 958
				}
			],
			[
				{
					"reserveDays": 216.4,
					"supplied": 58.4,
					"suppliedKm3": 683
				},
				{
					"reserveDays": 217.1,
					"supplied": 64.8,
					"suppliedKm3": 757
				},
				{
					"reserveDays": 217.7,
					"supplied": 71,
					"suppliedKm3": 831
				},
				{
					"reserveDays": 218.4,
					"supplied": 77.3,
					"suppliedKm3": 903
				},
				{
					"reserveDays": 218.7,
					"supplied": 83.4,
					"suppliedKm3": 975
				}
			],
			[
				{
					"reserveDays": 217.1,
					"supplied": 55,
					"suppliedKm3": 698
				},
				{
					"reserveDays": 217.7,
					"supplied": 60.8,
					"suppliedKm3": 773
				},
				{
					"reserveDays": 218.3,
					"supplied": 66.6,
					"suppliedKm3": 847
				},
				{
					"reserveDays": 218.9,
					"supplied": 72.4,
					"suppliedKm3": 920
				},
				{
					"reserveDays": 219.3,
					"supplied": 78.1,
					"suppliedKm3": 992
				}
			],
			[
				{
					"reserveDays": 217.6,
					"supplied": 52,
					"suppliedKm3": 713
				},
				{
					"reserveDays": 218.1,
					"supplied": 57.4,
					"suppliedKm3": 788
				},
				{
					"reserveDays": 218.8,
					"supplied": 62.8,
					"suppliedKm3": 862
				},
				{
					"reserveDays": 219.3,
					"supplied": 68.2,
					"suppliedKm3": 935
				},
				{
					"reserveDays": 219.7,
					"supplied": 73.5,
					"suppliedKm3": 1008
				}
			]
		]
	}
};
