// The glossary's articles for the "Scenarios and licensing" topic (category
// 'licensing' in tips.ts): scenarios, the published baseline, licence
// applications and evidence packs. Same shape and rules as articles.ts, in
// the tips' order. A module of its own, like articles-data.ts, so the /help
// pages load the glossary's long text in chunks each under the bundle guard's
// per-chunk ceiling (vite.config.ts helpArticlesChunk); content.ts joins them.

import type { HelpArticle } from './types';

export const LICENSING_ARTICLES: Record<string, HelpArticle> = {
	// ---- Scenarios and licensing -------------------------------------------
	'published-baseline': {
		long: 'An editor publishes a run from Runs & results with **Publish this run**, with the catchment’s restriction notice. It is what people outside the model read: farmers see their own farm’s figures from it, share links show it, and an applicant’s application starts from it. Publishing another run replaces it; the earlier publications stay on record. With nothing published, farmers see no figures and an applicant can’t start an application.',
		aliases: ['baseline', 'publication', 'publish', 'published run', 'restriction notice'],
		related: ['run', 'application', 'roles'],
		source: 'docs/data-model.md § Published baseline; docs/design/farmer-view.md'
	},
	'scenario': {
		long: 'A scenario is a named, ordered list of changes on a base run: raise a dam by 20 %, replace a crop, remove a farm, add a transfer, scale the rain by −10 %. It runs and compares against its base without copying the project, and because it keeps the base’s ids every change lines up in Compare runs. Editors make scenarios on the Scenarios tab to explore; a licence application is a scenario an applicant makes on the published baseline.',
		aliases: ['what-if', 'override', 'overrides', 'base run'],
		related: ['run', 'application'],
		source: 'docs/scenarios.md'
	},
	// ---- Scenario changes, their classes and cumulative impact ----------------
	'base-run': {
		long: 'A scenario never reads the project’s model as it stands now. It takes the inputs one saved run stored (the model, the settings and every series), applies its changes to them in order, and runs the result. Editing the model afterwards changes nothing in the scenario, and its comparison is always against the run it started from.\n\nA new scenario starts on the published run when there is one, else on the latest; any run that isn’t itself a scenario run can be picked. A licence application always starts on the published baseline. The base run can’t be deleted or trimmed while a scenario uses it.\n\nRebase onto another run moves a team scenario to another run of the model with the same changes. Check lists first any change that no longer applies there (a hydrological unit removed since, say); after the rebase such a change is marked as not applying, and the scenario can’t run until it is removed. A scenario run keeps the base it was made on, so until the scenario is run again its comparison says it still reads the earlier base.',
		aliases: ['base', 'rebase', 'rebasing', 'scenario base'],
		related: ['scenario', 'scenario-change', 'published-baseline', 'run'],
		source: 'docs/scenarios.md § Engine, § UI; frontend ScenariosTab.svelte, ScenarioEditor.svelte'
	},
	'scenario-change': {
		long: 'A scenario is an ordered list of changes, each aimed at one element by its id: change a hydrological unit’s field; add, remove or move a unit, or insert one on a reach; set a unit’s crop area; add, change or remove a crop, a transfer, land cover, a borehole, a demand object or a registered volume; change a setting; scale a rain series or the daily A-pan; scale demand; set or remove an EWR site’s rule table. Each change reads in words against the value it meets (“dam capacity 120 000 → 144 000 m³”), so a second change to the same value shows the first one’s result as the value it replaces.\n\nChanges apply in order, each to the model the ones before it left. One that can’t apply (its target is gone, a value is out of range, or it would leave a model the project couldn’t save: a loop, a second outlet, a duplicate name, crops on a gauge) is marked “Doesn’t apply” with the reason and changes nothing, and the scenario can’t run until it is removed or the base changes. Consecutive changes to one hydrological unit, or to one demand object, are checked together as one edit, so fields the model ties together (a supply rule and the dam it needs) can change in either order; a group that still breaks a rule is skipped whole, never half applied.\n\nA few edits have no change: a unit’s kind (remove it and add a new unit instead), and observed flow, which the run is scored against rather than driven by.',
		aliases: ['override', 'overrides', 'op', 'ops', 'add a change', 'doesn’t apply', 'edit group'],
		related: ['scenario', 'base-run', 'change-class', 'override-mode', 'scale-demand', 'scale-series'],
		source: 'docs/scenarios.md § Engine, § Op catalogue, § Not yet supported'
	},
	'change-class': {
		long: 'Every change in a scenario is labelled. A Proposal is the change being put forward: the proposer’s own dam, supply rule or river pump, crops, boreholes, demand objects or registered volume, a transfer between their own units, a new unit or a new structure on a reach. A Baseline assumption changes what the base run takes the catchment to be today: a setting or the calibration, rainfall or evaporation, an EWR site’s rule table or which gauges are EWR sites, the catchment’s split of runoff (land areas, flow shares), a dam’s survey date or sediment rate, bed losses in a reach, someone else’s hydrological unit, a crop’s factors or efficiency (they apply on every unit that grows the crop), and demand scaled across the whole catchment. Any baseline assumption puts the red “Baseline assumptions changed” callout above the list, here and on the compare page: an assessor will want to know why the baseline moved.\n\nWhat counts as the proposer’s is the ticked list The proposer’s hydrological units on a team scenario, plus anything the scenario itself adds or inserts; on a licence application it is the applicant’s own linked units, set by the server. Ticking a unit says whose a change is; it doesn’t limit where a change applies. The rules are conservative: a change that can’t be placed is a baseline assumption, and so is a new priority water user inserted above other farms, since whether a new use ranks above existing lawful use is the authority’s call.\n\nTo read a scenario as the impact of a proposal, keep baseline assumptions out of it: settle them in the project, or in a scenario of their own, so the comparison shows the proposal’s effect alone.',
		aliases: ['proposal', 'baseline assumption', 'baseline assumptions changed', 'classification', 'proposer', 'owned units'],
		related: ['scenario-change', 'application', 'scenario'],
		source: 'docs/scenarios.md § Classification: proposal or baseline assumption'
	},
	'override-mode': {
		long: 'Edit in the model tables opens the workspace’s own Network, Crops and Transfers tables on the scenario’s model: the base run’s inputs with the listed changes applied. Edit them as you would the real model, then Record: the app works out the changes that turn the model it loaded into the one you edited (crops first, then units removed, unit fields, units added or inserted, moves, crop areas, transfers, land cover, boreholes and demand objects), checks each as the form would, and adds them in one go, so one Undo takes them all back. Nothing is recorded unless the whole list applies and gives back exactly the model you edited.\n\nA few edits have no change to record. The record panel names them and holds the rest back until they are undone: a unit’s kind, the outlet moved, a new unit that drains nowhere, a field a scenario can’t set on that kind of unit, and the capacity of a dam with a survey curve when the curve is left as it was (paste the enlarged dam’s survey with it, or add the capacity with the form). A dam capacity typed in the table keeps the surface area the table shows; to enlarge a dam along its own area–volume relation, add the capacity with the form instead. Registered volumes and settings aren’t in these tables: add them with the form. Row order is display only and isn’t recorded.',
		aliases: ['override mode', 'record', 'edit in the model tables'],
		related: ['scenario-change', 'scenario'],
		source: 'docs/scenarios.md § UI (override mode)'
	},
	'scale-demand': {
		long: 'Scale demand answers “what if everyone takes 85 %?” in one change. It multiplies what each target would take: for a hydrological unit the crop water requirement after effective rain and the soil-water store, so the abstraction scales while the crop areas, the irrigation efficiency and the return-flow share stay as they are; for an other water user its monthly demand. Pick whose demand (hydrological units or other water users), the new demand as a % of what they’d take, and optionally the units and the months it applies to (none ticked is all of them). For hydrological units, Part of their demand limits it to the crops, or to the demand objects of one category, on top of any scaling of the whole.\n\nScalings multiply: 90 % twice is 81 %. A cut never takes a domestic or municipal demand object below its basic-needs floor. On a full-allocation run it scales the registered use: 85 % asks for 85 % of each registered volume.\n\nIt is a proposal only when every unit it names is the proposer’s; with no units ticked it scales the whole catchment and is a baseline assumption. The outcome matrix and the seasonal outlook make their demand levels with the same change.',
		aliases: ['demand scale', 'demand factor', 'restriction', 'cut demand', '85 %'],
		related: ['change-class', 'demand-factor', 'basic-needs-floor', 'demand-level'],
		source: 'docs/scenarios.md § Op catalogue (demand.scale), Demand scaling'
	},
	'scale-series': {
		long: 'Scales one driving series of the base run: station rain, CHIRPS, forecast rain, an alternative gauge’s rain, reanalysis rain, or the daily A-pan evaporation. Change (%) is the change, −10 for 10 % less; the factor may run from 0 to 10. From and To limit it to those days (inclusive); either left empty reaches that end of the record. Missing days stay missing, so gaps are filled as in the base run.\n\nEach change scales one series. The sensitivity runs scale every rain series the project has together, so the CHIRPS bias correction stays as it is and the whole forcing moves; to model a wetter or drier climate, do the same, one change per rain series. The monthly A-pan means and the pan coefficient are settings (Change a setting); on a project with a daily A-pan series they reach only the days the series doesn’t cover, so an evaporation scenario there scales the series too. Observed flow can’t be scaled: the run is scored against it, it doesn’t drive the model.\n\nAlways a baseline assumption: the climate is not the proposer’s to change.',
		aliases: ['scale rain', 'rainfall scaling', 'climate scenario', 'less rain', 'series scale'],
		related: ['change-class', 'rain-final', 'apan', 'sensitivity-runs'],
		source: 'docs/scenarios.md § Op catalogue (series.scale), Which series scale'
	},
	'cumulative-assessment': {
		long: 'One application at a time can hide what several do together. Assess together takes two or more submitted or decided applications on the same base run and runs the baseline, each application alone and all of them combined, all on the current engine so every column compares.\n\nApplications that collide are refused, never merged: two that change the same field of the same element (both raise one dam), or one that removes what another changes or uses. Check they combine lists each conflict with the two changes behind it, and any change that applies alone but not with the others (two new dams given one name, flow shares past 100 %); until an applicant changes their application the set can’t be assessed.\n\nThe result has one row per measure: per EWR site the days the EWR is not met and the mean shortfall; per Reserve rule-table site the months met and the deficit; for the catchment the mean flow at the outlet, the water supplied to existing users and their share of demand met (a unit an application adds is its own proposal and is left out). Each row gives the baseline, each application alone with its change, all together with its change, and the interaction. Owners and editors run it; it adds nothing to the project’s runs. An application’s evidence report reads a completed assessment of it with every other submitted or decided application on its baseline, and says when there is none.',
		aliases: ['cumulative impact', 'assess together', 'combined', 'conflict', 'check they combine', 'assessment'],
		related: ['cumulative-interaction', 'application', 'scenario-change'],
		source: 'docs/scenarios.md § Cumulative impact (WP-3.11); NWA s27(1)'
	},
	'cumulative-interaction': {
		long: 'Interaction = (all together − baseline) − the sum over applications of (alone − baseline). When the applications draw on separate water it is close to zero: their effects add. It moves away from zero when they meet. Two abstractions on one stream can do less together than their sum, since the same water can only be taken once; a threshold measure such as days below the EWR can show more together, when each alone stays just above the line and together they cross it. A change shown as worse means together they do more harm than their separate effects suggest.\n\nRead it beside the combined change, not on its own: a small interaction on a large combined change is still a large combined change. Days and months are whole counts; volumes are in m³ or m³/day.',
		aliases: ['interaction', 'non-additive', 'sum of singles'],
		related: ['cumulative-assessment'],
		source: 'docs/scenarios.md § Cumulative impact (the report); frontend CumulativeAssessment.svelte'
	},
	'application': {
		long: 'Someone applying for a water-use licence (a developer, an agribusiness or their consultant) is added to the project with the **Applicant** role. They never see the model itself: they start an application on the published baseline, describe their proposed change as a scenario (a new or raised dam, a new abstraction, more land under irrigation), run it and see their results against the baseline: the Ecological Reserve, the catchment’s flow, their own hydrological units and the farms downstream. Other farms show only by an anonymous name.\n\nWhile it is a draft only the applicant and the people they share it with can see it. Once they **submit** it, its changes are frozen and it appears on the **Applications** tab, where the project’s owners and editors (the assessors) open it, read its runs and record a decision with reasons. The applicant can withdraw it, or reopen it as a draft. The assessors issue its evidence packs, and can **Assess together** several applications for their cumulative effect on the river.',
		aliases: ['applications', 'licence application', 'water-use licence', 'WULA', 'applicant', 'assessor', 'contributor', 'submit', 'decision'],
		related: ['scenario', 'published-baseline', 'evidence-pack', 'roles'],
		source: 'docs/ui.md § Applications (WP-3.3); docs/scenarios.md § Applications'
	},
	'evidence-pack': {
		long: 'An evidence pack is a run’s evidence report frozen as a hashed, versioned, signed document that stays the same once it is issued. An applicant attaches it to their water-use licence application, and anyone holding it can check it against the app with its short code on the public verify page. An editor drafts one from a run’s evidence report; it is signed, then issued, and can later be superseded by a new version or withdrawn.',
		aliases: ['pack', 'short code', 'verify', 'manifest', 'sign-off'],
		related: ['application', 'evidence-run'],
		source: 'docs/evidence-pack.md'
	},
	// ---- Evidence, packs and registered volumes ------------------------------
	'evidence-report': {
		long: 'The evidence report is the licensing document of one run, built whole by the server and drawn by the page. It has two modes. A **baseline** report is the project’s current nominated evidence run on its own. An **application** report is a scenario run, reported against the base run it was made on, with the change in every figure and the applicant’s statement. Open it with **Evidence report** beside **Report** on Runs & results, or from the head of a scenario’s comparison. Viewers and up read it.\n\nSome runs can’t be evidence at all, and the page says why instead of drawing the report: a run that isn’t the current nominated run (or an application run on it), a run on the removed legacy runoff model, or a forecast run. Otherwise the report opens with its checks (on screen only): each one passed, failed and stops issue, or failed and is only printed, with what was found and the way out, then **Expect questions about**, the points an assessor will raise.\n\nUntil it is issued as an evidence pack every page carries a draft stamp, and **Download draft PDF** prints it as such. The report always reads the runs as they are now; a pack freezes it.',
		aliases: ['licensing report', 'evidence mode', 'baseline evidence', 'draft stamp', 'expect questions about', 'refused report'],
		related: ['evidence-run', 'application', 'pack-issue-checks', 'evidence-pack'],
		source: 'docs/ui.md § Evidence report; docs/design/evidence-report.md'
	},
	'pack-issue-checks': {
		long: 'Only a report that may be issued becomes a pack. The checks that stop issue are: the baseline is the project’s current nominated run; the declared uncertainty rule is set and the ensemble it cites exists (and, for an application, the paired band); the application changes no baseline assumption, only the applicant’s own works; every river pump in the runs has a capacity; and, for an application, its own river abstraction leaves the EWR, or a set hands-off flow, in the river in every month it can take. The two river checks read the runs’ stored models, so they judge exactly what the pack cites.\n\nAt issue the server checks again, in one step: the pack is a draft, its stored manifest still hashes to its recorded hash, the live report may still be issued, a specialist has signed the current pack statement, each such signer’s registration has a current check (while the project requires it), both runs still carry the server’s stamp, and no erratum found since the draft applies to either run’s engine. If any fails, nothing is issued and the refusal names it.\n\nExploring stays free: a model with an uncapped pump or no hands-off flow still saves and runs; only a pack can’t be issued on it. Other checks are printed in the report without stopping issue.',
		aliases: ['stops issue', 'issue checklist', 'river pump capacity', 'hands-off condition', 'protects the EWR', 'baseline assumption'],
		related: ['evidence-report', 'pack-lifecycle', 'evidence-uncertainty-rule', 'hands-off-flow', 'errata-since'],
		source: 'docs/evidence-pack.md § What stops issue on the river, § Lifecycle'
	},
	'pack-lifecycle': {
		long: '**Draft.** An editor makes a pack from a run’s evidence report with **Create evidence pack**. It freezes the report as it is at that moment; a draft has no public page.\n\n**Signed.** A registered professional signs the draft. Only a draft can be signed, and a sign-off can’t be undone.\n\n**Issued.** An editor issues a signed draft once every line of its checklist is ticked. From then on its verify page answers publicly, with the signers’ names and registrations, and the server prints its PDF and builds its reproduction bundle. Only one pack of an application (or of the baseline evidence) is issued at a time.\n\n**Superseded.** A change of evidence is a new version (**New version…**), drafted from the same run’s report as it stands now. When it is issued, the old one is marked superseded and its verify page points to the newer version. Nothing is edited.\n\n**Withdrawn.** An editor withdraws a pack, at any stage, with a reason of up to 1 000 characters. The verify page then says it is withdrawn and gives the reason, so write it for the licensing authority, not the team. Withdrawing can’t be undone.\n\n**Delete** is only for an unsigned draft. A signed draft is withdrawn instead, and a pack that was issued is never deleted, nor is its project, so its verify link keeps answering for as long as the licence record is kept. Issuing and withdrawing ask for a fresh code, from your authenticator app or by email. The project’s editors (and the application’s owner) get an email when a pack is issued or withdrawn.',
		aliases: ['draft', 'issue', 'issued', 'superseded', 'withdraw', 'withdrawn', 'new version', 'delete draft', 'pack status'],
		related: ['evidence-pack', 'pack-issue-checks', 'pack-signoff', 'pack-short-code'],
		source: 'docs/evidence-pack.md § Lifecycle, § Notices'
	},
	'manifest-hash': {
		long: 'The manifest is what a pack is: its id and version (and the hash of the version it replaces), the project, the engine version, and the whole evidence report: every setting, the model, the hash of every input series, the results, the flags and checks, the methodology and errata cited, and the locality map. Its SHA-256 is taken over a canonical JSON text (RFC 8785), so the same content always gives the same hash, and any change to the evidence gives another.\n\nNot in the hash: the pack’s status, when and by whom it was drafted or issued, a withdrawal reason and its successor, so a pack keeps its hash from draft to withdrawn. The sign-offs aren’t in it either: each signer’s statement names the hash instead. The PDF and the reproduction bundle have hashes of their own; the bundle contains the manifest.\n\n**Download manifest** saves those canonical bytes, so the file checks on the verify page; a copy saved pretty-printed still matches, since the page compares the canonical form too. If the stored manifest ever stops matching its recorded hash, the pack page says so in red and the pack can’t be issued.',
		aliases: ['manifest', 'SHA-256', 'hash', 'fingerprint', 'canonical JSON', 'RFC 8785', 'download manifest'],
		related: ['pack-short-code', 'reproduction-bundle', 'pack-pdf', 'evidence-pack'],
		source: 'docs/evidence-pack.md § What a pack holds, § What is hashed, and what isn’t'
	},
	'pack-short-code': {
		long: 'The short code is the first 12 hexadecimal digits of the manifest hash, written xxxx-xxxx-xxxx. It is printed on every page of an issued pack, beside the full hash and the verify address, and it is not a secret.\n\nThe **verify page** is public: no account or sign-in. Enter the code (any case, with or without dashes) or the full 64-digit hash, and it shows only what the pack itself prints: whether it is issued and current, superseded (with the newer version’s code) or withdrawn (with the reason), the catchment, version, issue date, engine and report format, the methodology statement, the manifest, PDF and bundle hashes, the errata the pack recorded and any found since, and each signer with their registration (self-declared, or checked against the register by whom and when). A draft, a pack withdrawn before issue, and an unknown code all give the same answer: no issued pack has this code.\n\nThe page can also check a file: choose a PDF, manifest or reproduction bundle and it is hashed in your browser, never uploaded, and compared with the recorded hashes. Verifying proves that this app issued a pack with that content, who signed it and whether it still stands; whether the results follow from the inputs is the reproduction bundle’s job. A withdrawal shows on the page at once.',
		aliases: ['short code', 'verify', 'verify page', 'verify code', 'verify link', 'check a file'],
		related: ['manifest-hash', 'pack-lifecycle', 'reproduction-bundle', 'errata-since'],
		source: 'docs/evidence-pack.md § The short code, § Verification; docs/ui.md § Verify page'
	},
	'pack-pdf': {
		long: 'When a pack is issued, the server prints its page in a headless browser, from the frozen manifest, with its stamp, verify line and sign-offs on every page. The PDF is stored under its own SHA-256, in storage that refuses any other bytes under that name and that the app can’t overwrite or delete; the first PDF recorded stands. From then on the verify page shows its hash, and the downloaded file hashes to it (sha256sum pack.pdf).\n\nThe PDF shows the pack as it was when printed: a later supersede or withdrawal is for the verify page to say. Until the server’s PDF is recorded, **Download PDF** on the pack page prints the page in your own browser, which is not the recorded PDF. A print that fails is tried again on its own (up to three times); after that an editor can ask again with **Try again**.\n\nThe PDF names every hydrological unit with its figures, as the manifest does, so it is the assessors’ document: share links and the applicant’s view don’t offer it.',
		aliases: ['pack PDF', 'PDF SHA-256', 'download PDF', 'server PDF'],
		related: ['manifest-hash', 'pack-short-code', 'applicant-copy', 'report-pdf'],
		source: 'docs/evidence-pack.md § The PDF'
	},
	'reproduction-bundle': {
		long: 'Issuing a pack builds a ZIP with everything needed to re-run it: an index with the SHA-256 of every file, the manifest, each run’s stored input snapshot and results, every input series as a CSV named by its hash, the application’s changes, and a README saying which engine version to use. It is checked, stored and its hash recorded in the same step as the issue; if that fails, nothing is issued. The verify page publishes its hash.\n\nAnyone holding the bundle can re-run both runs with only the bundle and the app’s source at the pack’s engine version, with no database, account or network (pnpm reproduce:pack). Each check is printed: the files match their hashes, the manifest hashes to the pack’s hash, the inputs and changes are the manifest’s, the stored results are the manifest’s, and re-running each run gives the same results digest. A run made with another engine version is expected to differ, and the output says which version to use.\n\nThe server also re-runs a pack from its stored bundle after issue, and the pack page says what it found: reproduced, not reproduced (with each failed check), another engine, or still running. An editor can ask for it again (after a failure, or on a newer engine; the new outcome is kept beside the old). That is the app’s own claim, never printed and not on the verify page: an assessor repeats it with the bundle. The bundle names every unit, so it goes to the assessors, not through share links or the applicant.',
		aliases: ['bundle', 'reproduce', 'reproduction', 're-run', 'results digest', 'reproduce:pack', 'reproduced on the server'],
		related: ['manifest-hash', 'pack-short-code', 'send-to-authority'],
		source: 'docs/evidence-pack.md § Reproduction'
	},
	'errata-since': {
		long: 'An erratum is a known bug in a version of the engine, recorded with what goes wrong, when it applies and the version that fixes it. A pack records the errata of its runs’ engines (and of the engines their fits were made with) when it is drafted, and the signer reads them before signing.\n\nAn erratum added to the list later that applies to either run is shown apart, never added to the pack: on an issued pack it is listed as found since issue, on the pack page, the verify page and the applicant’s view, while the pack, its PDF and its hash stay as they were. On a draft it blocks issue: draft the pack again, which records it, then sign and issue that one. So a pack is only ever issued with every erratum known at the time.',
		aliases: ['errata', 'erratum', 'known bug', 'found since issue', 'errata found since this draft'],
		related: ['pack-lifecycle', 'pack-short-code', 'signoff-statement'],
		source: 'docs/evidence-pack.md § Verification (errataFoundSince); docs/ui.md § Evidence pack'
	},
	'signoff-statement': {
		long: 'A registered professional signs a run (or an evidence pack) as it was made. The dialog asks for their name, registration body (SACNASP or ECSA), category, field and number; candidate and certificated categories can’t sign, since they work under a professional’s supervision and that professional signs, and a field outside catchment hydrology gets a warning to sign only within their competence. They then tick each of ten confirmations on its own (who they are, competence, conflicts of interest, the input data, the calibration, the EWR tables, the network or the proposed works, assurance levels and demand, plausibility, and that they read the methodology, limitations and errata), read the run’s known limitations and the errata of its engine to the end, and say what the sign-off covers.\n\nThe server keeps a SHA-256 of the exact statement shown, so a signature is bound to those words and versions; a statement that changed since the dialog opened is refused. A sign-off is permanent: it can’t be changed or withdrawn, only followed by another. It covers this run only, makes no finding on whether a water use is lawful, doesn’t cover dam safety, relies on the app’s calculations, and is not a signature on any form the authority requires. The registration details are the signer’s own declaration unless the host has recorded a check against the register.\n\nA report whose run is nominated as evidence, or an impact report, says in bold on its cover when it isn’t signed: not for use as evidence in a licence application.',
		aliases: ['sign-off', 'sign off', 'signed off', 'confirmations', 'registered professional', 'SACNASP', 'ECSA', 'statement confirmed'],
		related: ['pack-signoff', 'report-disclaimer', 'evidence-run', 'errata-since'],
		source: 'docs/legal/disclaimer-review.md § 2; docs/ui.md § Report'
	},
	'pack-signoff': {
		long: 'A pack is signed against the pack statement: the run statement’s ten confirmations plus an eleventh naming the pack’s version and manifest hash. Only a draft is signed.\n\nThere are two kinds. **Specialist for the applicant** is the professional responsible for the evidence, and issue needs one. **Reviewed for the responsible authority** is an optional second sign-off by an editor, never enough on its own. The evidence is the applicant’s, so the applicant’s own specialist normally signs: the project owner marks a member of the applying party as its specialist, and that person signs the draft packs of their party’s applications. Editors may sign too.\n\n**Registration check.** The app checks no registration itself. Someone at the host looks the signer up on the public SACNASP or ECSA register, and an owner, or an editor acting for the responsible authority, records what they found under Registration checks on the Project page. A check is current for a year. While the project requires it (on by default), issue waits until each specialist signer has a current check; the verify page then says “checked against the register by …”, and every other registration reads “self-declared”.\n\nSigning, issuing and withdrawing ask for a code from the last 10 minutes (from your authenticator app, or by email), and you need two-step sign-in set up before your first sign-off. The signer’s name, registration and date are shown publicly on the verify page, even after a withdrawal, for as long as the licence record is kept. A new known limitation or erratum since the signature means signing again.',
		aliases: ['sign the pack', 'specialist', 'specialist for the applicant', 'reviewed for the responsible authority', 'registration check', 'self-declared', 'fresh code', 'two-step'],
		related: ['signoff-statement', 'pack-lifecycle', 'responsible-authority', 'pack-issue-checks'],
		source: 'docs/evidence-pack.md § Lifecycle, § Signing, § Retention'
	},
	'report-disclaimer': {
		long: 'Every catchment report ends with the disclaimer, all five paragraphs and its version, and its key points are in the **Read this first** box on the cover and in the footer of every printed page. In short: the results are estimates from a computer model, not measurements or predictions, and can be wrong; the report supports, and doesn’t replace, the specialist hydrology report, and is not an authorisation to use water (only the responsible authority decides that under the National Water Act); modelled shortfalls, curtailment and equitable shares are not official restrictions or allocations; whoever made the run chose its inputs, and a sign-off is that professional’s own statement; and the operator of the software didn’t prepare the report, checks none of it and, as far as the law allows, accepts no responsibility to anyone who relies on it. Have the results checked by a qualified hydrologist before acting on them. Nothing in a report covers the safety of a dam.\n\nOne line of it heads every CSV of a run’s results, and a **Read this first** sheet opens the run’s .xlsx workbook. A sign-off records the disclaimer version the signer was shown. Farmers don’t see it: their farm page and alert emails carry their own short lines.',
		aliases: ['disclaimer', 'read this first', 'liability', 'not an authorisation', 'model estimates'],
		related: ['signoff-statement', 'restriction-notice', 'equitable-share'],
		source: 'docs/legal/disclaimer-review.md § 1'
	},
	'responsible-authority': {
		long: 'Under the National Water Act only the responsible authority decides a licence and what evidence it accepts: the Department of Water and Sanitation or a catchment management agency. An editor names it, with its office, on the Project page, and every evidence report says whom it is for in its **For** row (or that no authority is named).\n\nThe owner marks the members who act for the authority. They record its decisions on applications, and they can endorse a published baseline (Runs & results, Publication: **Endorse as the responsible authority**, with an optional note). An endorsement is recorded once, with their name, and can’t be changed or withdrawn. An evidence report on a baseline nobody endorsed says “Not endorsed by the responsible authority” and carries a caution on page 1. A pack freezes both when it is drafted: an authority named or an endorsement made later changes the live report, never the pack.',
		aliases: ['for', 'endorsement', 'endorsed', 'not endorsed', 'acts for the responsible authority', 'CMA', 'DWS'],
		related: ['published-baseline', 'evidence-report', 'send-to-authority', 'pack-signoff'],
		source: 'docs/evidence-pack.md § The responsible authority; docs/ui.md § Project (Responsible authority)'
	},
	'full-authorised-use': {
		long: 'Page 1 of an application’s evidence report judges it twice. The headline is **against full authorised use**: the baseline and the application both run again with every holder taking their full registered volume (the full allocation mode). A proposal that passes only because other holders don’t take their whole entitlement would hurt them as soon as they do, and the authority weighs existing lawful use and the effect on other users. Beside it, a table gives that volume by how it is held: only a licence or an existing lawful use verified under s35 is an entitlement; a WARMS registration, a claimed existing lawful use, a general authorisation and Schedule 1 use are not. It shows totals only, never a holder.\n\nThe second board is **against modelled current use**: the baseline as it ran, so existing use is what the model found holders use; it answers what changes tomorrow.\n\nThe pair is two model runs, so an editor starts it from the evidence report with **Run at full authorised use**. It is kept for that application run and read only while it was made on the baseline’s engine with the project’s outcome settings as they are now; otherwise the report prints a fixed “Not assessed” row saying why, and the button reads **Run it again**. A pack freezes whichever board page 1 had when it was drafted.',
		aliases: ['full authorised use', 'authorised impact', 'existing authorised use', 'modelled current use', 'entitlement', 'run at full authorised use'],
		related: ['allocation-mode', 'authorisation-type', 'licence-impact-year-class', 'registered-volume'],
		source: 'docs/evidence-pack.md § Both impact bases'
	},
	'licence-impact-year-class': {
		long: 'The baseline’s complete water years are ranked by their natural flow at the outlet and split into classes, terciles by default (dry, middle, wet) or quintiles, by the project’s outcome settings. Each column sets the baseline beside the application over the same years. The **annual waterfall** is the mean a year at the outlet: natural flow, existing use in the baseline, the proposed extra use (application minus baseline), the rest (dams, storage, groundwater, land cover) and the flow left. Below it, the **months below the Reserve** at the project’s Reserve site, baseline, application and the change (or the days below the pragmatic EWR, when the runs have no rule table).\n\nThe **verdict** is written from the months below the requirement, never from the annual totals, and has no colour: it reports what the runs did, it doesn’t recommend. A class with fewer than 3 years reads “Not enough years”. Existing use is the baseline’s as that run modelled it; for existing authorised use, compare against a baseline run at full allocation. In an evidence report the board is built into the report, so a pack freezes it.',
		aliases: ['year class', 'licence impact', 'annual waterfall', 'verdict', 'dry years', 'terciles', 'quintiles'],
		related: ['full-authorised-use', 'reserve-compliance', 'natural-flow', 'water-year'],
		source: 'docs/ui.md § Report (Impact by year class); docs/model.md §2.14a'
	},
	'pack-share-link': {
		long: 'An editor shares an issued pack by a read-only link (**Share link…** on the pack page), so an NGO, a catchment forum or an assessor without an account can read it during a comment period; an applicant can link their own application’s pack the same way. You choose who it is for and how long it lasts, copy it once, and can withdraw it at any time.\n\nThe link shows what the verify page shows and, while the pack is issued, figures from its frozen manifest: the river’s rows (Reserve months met per site, days below the EWR, no-flow days) with their bands, Reserve compliance at each EWR site, and the change by calendar month. Volume rows appear only when at least 5 farms hold water and the application changed no baseline assumption. It never shows a user’s, farm’s or allocation’s figures or name, the other applications, the settings, model or inputs, the applicant’s statement, or anyone but the signers; nor the PDF, the manifest or the bundle.\n\nReaders can post public comments while the pack is issued and a link is live; every edit is kept. If the pack is later superseded or withdrawn, the link keeps working but shows only its standing, the reason or the newer version’s code, and the comments: no figure.',
		aliases: ['share link', 'share a pack', 'public comments', 'public participation', 'comment period'],
		related: ['pack-lifecycle', 'pack-short-code', 'allocation-viewer-access'],
		source: 'docs/evidence-pack.md § Sharing and comments'
	},
	'send-to-authority': {
		long: 'The pack’s PDF and reproduction bundle name every water user with their figures, so they go to the authority that decides the licence, not through the applicant. On an issued pack, an editor picks **Send to the authority…** and chooses among the members the owner marked as acting for the responsible authority (all, or some), with an optional note.\n\nEach gets an email naming the pack, its version, code and the authority, with the note. It carries **no file and no download link**: it links the pack’s page, where the member, signed in and still an editor, downloads the PDF and bundle, and the public verify page. So a forwarded email opens nothing. Only an issued pack can be sent. The history records who it went to and whether a note went, never the note itself. Addresses outside the app aren’t offered.',
		aliases: ['send', 'send to the authority', 'authority email'],
		related: ['responsible-authority', 'reproduction-bundle', 'pack-pdf'],
		source: 'docs/evidence-pack.md § Sending it to the authority'
	},
	'applicant-copy': {
		long: 'An applicant, and the people they share their application with, read its issued packs in a view of their own: their own hydrological units by name, every other farm or water user downstream only by a number (as in their results), and the river’s figures. The assessors’ copy, its PDF and its bundle name everyone; this view doesn’t.\n\n**Make a printable copy** has the server print that view as a PDF, recorded once with its own SHA-256 (asking again changes nothing). Its first page and every footer say “Applicant’s copy: other water users’ figures withheld. Not the pack.” with the verify address, the pack’s code and its manifest hash. File it where the application needs the evidence: what an applicant files reaches the interested and affected parties, so it withholds the others’ figures. It is not hashed as the pack, never replaces it, and the verify page knows nothing of it: the authority checks the pack itself.',
		aliases: ['printable copy', 'applicant’s copy', 'applicant pack view', 'your copy'],
		related: ['application', 'pack-pdf', 'pack-short-code'],
		source: 'docs/evidence-pack.md § Applicants'
	},
	'restriction-notice': {
		long: 'When an editor publishes a run as the baseline, the publication carries the water user association’s restriction notice: a level (none, advisory or restricted), an optional cut in %, when the next update is expected, and the WUA’s own words in each language it writes. Farmers read the notice first on their farm page, in their language (or another one written, when theirs is empty). The app never writes restriction wording itself. An editor changes the notice with **Edit notice** without publishing again.\n\nThe notice is the WUA’s. The model’s curtailment targets and equitable shares are not restrictions or allocations: only a notice from a body with the legal power to make one is. The drought restriction rule under Settings is separate: a model input that cuts demand in a run, which can be started from the published notice.',
		aliases: ['notice', 'WUA notice', 'advisory', 'restricted', 'restriction level', 'edit notice'],
		related: ['published-baseline', 'drought-restriction', 'report-disclaimer'],
		source: 'docs/ui.md § Runs & results (Publishing a run); docs/data-model.md § Publications'
	},
	'registered-volume': {
		long: 'An allocation is one volume a year, from one water source (surface or groundwater), held under one authorisation, for a hydrological unit or other water user, with its purpose and the dates it is valid (inclusive; either end may be open). The registration or licence number and the property are kept to match it to a unit; the registered user’s name, a reference and the file it was imported from (name and SHA-256) are kept beside it. A unit may have several, such as a registration and a later licence, or surface and groundwater: the comparison adds up every one in force on each day.\n\nEvery run’s input carries the volumes in force (never the names). So a stored run replays with the volumes it ran on, changing a volume makes the latest run out of date, and comparing two runs lists the volumes that changed. A scenario can set or remove a volume for one run.\n\nA registered volume is what an authorisation says, not an entitlement, and the app never decides whether a use is lawful.',
		aliases: ['allocation', 'allocations', 'registered', 'licensed volume', 'volume', 'valid from', 'valid to', 'registration number', 'property', 'registered user', 'holder'],
		related: ['authorisation-type', 's21-water-use', 'registered-vs-modelled', 'allocation-mode', 'allocation-viewer-access'],
		source: 'docs/allocations.md § What is stored'
	},
	'authorisation-type': {
		long: 'How a volume is held, in the National Water Act’s terms:\n\n**Registration (WARMS)**: registered with DWS (GN R1352 of 1999). A registration is not an entitlement and doesn’t confirm that a use is lawful.\n\n**Licence**: a water-use licence (s40).\n\n**General authorisation**: use within a published general authorisation (s39, such as GN 538).\n\n**Schedule 1 (permissible use)**: small uses allowed without a licence (s22(1)(a)(i)). They aren’t registered with DWS, so a farmer’s registered totals leave them out.\n\n**Existing lawful use, claimed**: claimed or registered under s32, not verified.\n\n**Existing lawful use, verified under s35**: only this verification confirms an existing lawful use.\n\nOn import, words such as “existing”, “ELU” or “s32” read as claimed; only an explicit “verified” or “s35” reads as verified. Against full authorised use, only a licence and a verified existing lawful use count as entitlements.',
		aliases: ['authorisation', 'WARMS', 'registration', 'licence', 'general authorisation', 'Schedule 1', 'existing lawful use', 'ELU', 's35', 's32', 'permissible use'],
		related: ['registered-volume', 'full-authorised-use', 'ga538'],
		source: 'docs/allocations.md § What is stored, § Importing (Authorisation words)',
		countries: ['ZA']
	},
	's21-water-use': {
		long: 'WARMS registers water per s21 water use, per property. **Taking water (s21a)** is a volume a year, compared with the unit’s modelled use. **Storing water in a dam (s21b)** registers the dam’s storage: the row has no volume (it is shown as “Storage only (s21b)”), is always surface water, and is compared only with the capacity of the dam the run modelled, never counted, capped or scaled as a take. A take can also state a storage beside its volume.\n\nOther s21 uses (21(c) to 21(k)) are refused on import, as is a row whose use or unit can’t be read: they are never guessed. Whether filling a dam is also an s21(a) take is a question for the catchment’s hydrologist.',
		aliases: ['water use', 's21', '21a', '21b', 'taking water', 'storing water', 'storage only'],
		related: ['registered-volume', 'registered-storage', 'warms-import'],
		source: 'docs/allocations.md § What is stored, § Importing (One row per s21 water use)',
		countries: ['ZA']
	},
	'licence-conditions': {
		long: 'A licence may limit when and how fast water is taken. Each volume can record the **months** water may be taken in (none ticked means none stated: all year), a **maximum rate** in m³/s, and up to 20 **other conditions** in the licence’s own words. The list sums them up in one line, such as “Oct–Mar only · at most 0.05 m³/s · 2 conditions”.\n\nOnly a run whose allocation mode is **cap** keeps to the months and the rate: the unit takes nothing from that source in a closed month, and at most the rate × 86 400 m³ a day. The plain comparison and a full-allocation run don’t read them, and conditions in words are only shown, never applied.',
		aliases: ['conditions', 'months of use', 'maximum rate', 'licence condition'],
		related: ['registered-volume', 'allocation-mode', 'cap-held-back'],
		source: 'docs/allocations.md § What is stored'
	},
	'warms-import': {
		long: 'WARMS has no public interface: a CMA or DWS sends an extract. **Import** reads a WARMS extract or the app’s CSV template (download it from the Import sheet). For a WARMS extract you record how you obtained it, the DWS or CMA letter or terms. The file is a CSV, comma or semicolon separated, UTF-8, up to 2 MB and 5 000 rows; save a spreadsheet as CSV first.\n\nColumns are found by their headings; one the importer doesn’t know is listed as not read, never guessed. Each row is read by its water use (21(a) or 21(b)) and its unit; a row that can’t be read for sure is a row problem and isn’t imported, and an extract with no water-use column is refused whole. A heading that looks like an ID number, passport, phone or email column refuses the whole file before anything is stored.\n\nRows are matched to units by the same registration number as an earlier import, then the same property, then a hydrological unit or water user whose name equals the row’s farm (ignoring case and spacing); two units with the same name match neither. The preview lists rows with problems first, then unmatched rows with a picker. The same file can’t be imported twice into a project, and **Remove this import** deletes the file’s record and every row it brought.',
		aliases: ['import', 'WARMS extract', 'CSV template', 'imported files', 'remove this import', 'matching', 'not matched'],
		related: ['registered-volume', 's21-water-use', 'authorisation-type'],
		source: 'docs/allocations.md § Importing',
		countries: ['ZA']
	},
	'registered-vs-modelled': {
		long: 'For a run, per hydrological unit or water user, water source and water year (October to September). **Modelled use** is the run’s supply summed over the year, from the unit’s own dam, the river and boreholes: groundwater is what boreholes pumped (to the crops or into the dam), and surface water the rest, less borehole water pumped into the dam and drawn out again in the same year. **Registered volume** is each volume in force × the days it is valid that year ÷ the days in the year.\n\nEach year reads **above registered** (modelled use more than the volume × (1 + the band)), **within band**, **below registered**, **no registered volume** (use with nothing in force) or **no use, none registered**; the band is ±10 % unless the project sets another. A part year (a run that covers only part of a water year) compares those days with the volume prorated to them, is marked part, and isn’t counted with the whole years. A forecast run is compared on its record only. Volumes not matched to a unit, or on a unit the run doesn’t have, are counted, not compared.\n\nIt is not a finding: modelled use is modelled, not metered, and a registered volume can be missing, out of date or held by someone else. The Reserve, other users’ priority and licence conditions aren’t applied here, only in a cap run. The Allocations page uses the project’s volumes and band now; an evidence report uses those each run stored, so an older run can differ.',
		aliases: ['modelled use', 'above registered', 'within band', 'below registered', 'no registered volume', 'part year', 'modelled, not metered', 'over and under use'],
		related: ['registered-volume', 'allocation-band', 'allocation-mode', 'water-year', 'cap-held-back'],
		source: 'docs/allocations.md § The comparison, § What the comparison is not'
	},
	'registered-storage': {
		long: 'For a unit with a dam, the sum of its registered storage (its s21(b) rows, and storage stated on a take) is set beside the dam capacity the run modelled, with the difference (capacity minus registered storage). It reads **over** when the dam is larger than the storage registered for it, **under** when smaller, and **unregistered** for a dam with no storage registered, banded like a year’s use.\n\nIt is arithmetic only. A registered storage is never part of the volume a year’s use is compared with, and whether filling the dam is also a take is a question for the catchment’s hydrologist.',
		aliases: ['registered storage', 'storage', 'dam capacity vs registered'],
		related: ['s21-water-use', 'dam-capacity', 'registered-vs-modelled'],
		source: 'docs/allocations.md § The comparison (Storage)'
	},
	'cap-held-back': {
		long: 'A run made with the allocation mode **cap** says which limit held use back. For each unit, source and water year it counts the days the source took all the room it had and the unit still went short, split into days the year’s volume was used up, days at the maximum rate and days outside the months of use, beside the years the volume was used up (“The cap held use back on 80 days in 1 water year: 80 with the volume used up.”).\n\nThe Allocations page shows it under the picked unit’s water years, the run’s summary CSV has an allocation cap table, and an evidence report prints it as “What the cap held back”, with “Not capped” for a source the run didn’t cap. Unlike the comparison, it counts the whole run, a forecast included. A run from an engine older than 1.40.0 has only the years: run the model again for the days.',
		aliases: ['cap', 'cap run', 'limit bound', 'volume used up', 'what the cap held back'],
		related: ['allocation-mode', 'licence-conditions', 'registered-vs-modelled'],
		source: 'docs/allocations.md § What is stored (cap), § In the evidence report'
	},
	'allocation-viewer-access': {
		long: '**Owners and editors** see every volume, number and date, and the registered users’ names, and they make every change.\n\n**Viewers** see totals per water source held by 5 or more registered users (the volume and storage in force today, and a run’s use against them by water year), and never a name. An owner can let viewers see each farm’s volumes under **What viewers see**; do so only if every viewer works for, or was appointed by, your organisation, since viewers can be outsiders (an NGO commenting on an application).\n\n**Farmers** see only their own farm’s totals on their farm page, with no name or registration number. **Share links, pack links and the verify page** show no volumes. An **issued evidence pack** names the applicant’s own units; every other unit is in totals at 5 or more units, with no names. The history records registration numbers and counts, never names.',
		aliases: ['what viewers see', 'names of registered users', 'privacy', 'who sees names'],
		related: ['registered-volume', 'roles', 'pack-share-link'],
		source: 'docs/allocations.md § Who sees what'
	},
};
